In [18]:
import pandas as pd
import numpy as np
import os
import re
pd.set_option('display.max_rows', None)

DATA_DIR = "datasets"  # folder with your 39 CSVs
files = [f for f in os.listdir(DATA_DIR) if f.endswith(".csv")]
print(f"Found {len(files)} files")

# First pass: just look at shape and columns of every file
inventory = []
for f in files:
    path = os.path.join(DATA_DIR, f)
    try:
        df = pd.read_csv(path)
    except UnicodeDecodeError:
        df = pd.read_csv(path, encoding="latin1")
    try:
        inventory.append({
            "file": f,
            "rows": df.shape[0],
            "cols": df.shape[1],
            "columns": list(df.columns)
        })
    except Exception as e:
        print(f"Failed to read {f}: {e}")

inv_df = pd.DataFrame(inventory)
pd.set_option('display.max_colwidth', None)
print(inv_df[["file", "rows", "cols"]])

Found 40 files
                                   file  rows  cols
0          RS_Session_254_AU_1496.A.csv     7     3
1        RS_Session_254_AU_2384.C.i.csv    27     4
2           RS_Session_254_AU_697_1.csv    37     3
3          RS_Session_255_AU_2349_2.csv    35     3
4           RS_Session_255_AU_305.A.csv     2     4
5           RS_Session_255_AU_749.C.csv     3     3
6           RS_Session_256_AS_154.A.csv     3     3
7          RS_Session_256_AU_2673_1.csv    16     3
8      RS_Session_256_AU_2673_2.ii_.csv    26     4
9            RS_Session_256_AU_95_C.csv    33    11
10       RS_Session_257_AS_71_A.ii_.csv    14     3
11         RS_Session_258_AU_2037_A.csv     4     4
12          RS_Session_258_AU_429_1.csv    35    18
13          RS_Session_258_AU_429_B.csv     4     3
14           RS_Session_258_AU_91_1.csv    35    18
15         RS_Session_259_AU_2028_A.csv     4     3
16         RS_Session_259_AU_2032_A.csv    11     2
17         RS_Session_259_AU_2474_A.csv     3     4
18   RS_Session_259_AU_2477_C_and_D.csv     4     3
19         RS_Session_259_AU_2836_A.csv     5     3
20         RS_Session_259_AU_2837_A.csv    35     3
21         RS_Session_259_AU_2837_B.csv    91     2
22         RS_Session_259_AU_3475_1.csv    35     3
23    RS_Session_259_AU_3477_A_to_D.csv     5     3
24          RS_Session_260_AS_241_E.csv     3     5
25   RS_Session_260_AU_1872_A_and_B.csv     5    20
26    RS_Session_260_AU_2349_A_to_B.csv    35     4
27          RS_Session_263_AU_102_A.csv     5     5
28          RS_Session_263_AU_105_A.csv     5     3
29          RS_Session_263_AU_105_C.csv     4     3
30          RS_Session_263_AU_905_A.csv     4     2
31   RS_Session_265_AU_1355_A_and_B.csv     5     2
32         RS_Session_265_AU_2151_E.csv    35     3
33          RS_Session_266_AS_217_4.csv     6     2
34       RS_Session_266_AU_2960_B_i.csv    37     3
35  RS_Session_266_AU_2960_C_to_D_i.csv    32     3
36        RS_Session_266_AU_552_D_i.csv     4     7
37     RS_Session_266_AU_553_A_to_B.csv     6     3
38          RS_Session_267_AU_580_A.csv     4     3
39        RS_Session_267_AU_581_C_i.csv    37     5

In [16]:
def clean_column_names(df):
    """Standardize headers: strip whitespace, fix typos, lowercase-friendly."""
    df.columns = [str(c).strip() for c in df.columns]
    df = df.rename(columns={"hoi": "Sl. No."})  # fixes the typo in one file
    return df

def clean_numeric_column(series):
    """Convert messy numeric-looking columns to float, handling NA/approx/commas."""
    return (
        series.astype(str)
        .str.replace("approx.", "", regex=False)
        .str.replace(",", "", regex=False)
        .str.strip()
        .replace({"NA": np.nan, "N/A": np.nan, "-": np.nan, "": np.nan})
        .astype(float)
    )

def load_and_clean(filename):
    path = os.path.join(DATA_DIR, filename)
    try:
        df = pd.read_csv(path)
    except UnicodeDecodeError:
        df = pd.read_csv(path, encoding="latin1")
    df = clean_column_names(df)
    return df

In [17]:
theme_groups = {
    "ev_registration_trends": [
        "RS_Session_255_AU_749.C.csv",
        "RS_Session_256_AS_154.A.csv",
        "RS_Session_259_AU_2032_A.csv",
        "RS_Session_259_AU_2477_C_and_D.csv",
        "RS_Session_260_AU_1872_A_and_B.csv",
        "RS_Session_263_AU_905_A.csv",
        "RS_Session_265_AU_1355_A_and_B.csv",
    ],
    "state_wise_ev_data": [
        "RS_Session_254_AU_697_1.csv",
        "RS_Session_255_AU_2349_2.csv",
        "RS_Session_256_AU_95_C.csv",
        "RS_Session_258_AU_429_1.csv",
        "RS_Session_258_AU_91_1.csv",
        "RS_Session_259_AU_3475_1.csv",
        "RS_Session_260_AU_2349_A_to_B.csv",
    ],
    "charging_infrastructure": [
        "RS_Session_256_AU_2673_1.csv",
        "RS_Session_256_AU_2673_2.ii_.csv",
        "RS_Session_257_AS_71_A.ii_.csv",
        "RS_Session_259_AU_2474_A.csv",
        "RS_Session_259_AU_2837_A.csv",
        "RS_Session_259_AU_2837_B.csv",
        "RS_Session_265_AU_2151_E.csv",
        "RS_Session_266_AU_2960_B_i.csv",
        "RS_Session_266_AU_2960_C_to_D_i.csv",
        "RS_Session_267_AU_581_C_i.csv",
    ],
    "scheme_budget_and_subsidy": [
        "RS_Session_254_AU_1496.A.csv",
        "RS_Session_258_AU_2037_A.csv",
        "RS_Session_258_AU_429_B.csv",
        "RS_Session_259_AU_2028_A.csv",
        "RS_Session_259_AU_2836_A.csv",
        "RS_Session_259_AU_3477_A_to_D.csv",
        "RS_Session_263_AU_105_A.csv",
        "RS_Session_266_AS_217_4.csv",
        "RS_Session_266_AU_553_A_to_B.csv",
        "RS_Session_267_AU_580_A.csv",
    ],
    "sales_by_category": [
        "RS_Session_263_AU_102_A.csv",
        "RS_Session_263_AU_105_C.csv",
        "RS_Session_260_AS_241_E.csv",
    ],
    "global_comparison": [
        "RS_Session_266_AU_552_D_i.csv",
    ],
    "manufacturer_specific": [
        "RS_Session_255_AU_305.A.csv",
        "RS_Session_254_AU_2384.C.i.csv",
    ],
}

# quick check: did every file get assigned to a theme?
assigned = set(sum(theme_groups.values(), []))
unassigned = set(files) - assigned
print("Unassigned files:", unassigned if unassigned else "None — all files grouped")

Unassigned files: None — all files grouped

In [4]:
def build_registration_trends():
    frames = []
    for f in theme_groups["ev_registration_trends"]:
        df = load_and_clean(f)
        df["source_file"] = f
        frames.append(df)
        print(f"\n{f}:\n{df.head(2)}")  # inspect before deciding how to align columns
    return frames

frames = build_registration_trends()

RS_Session_255_AU_749.C.csv:
  Sl. No.  Year  Number of Electric Vehicles                  source_file
0       1  2019                       161314  RS_Session_255_AU_749.C.csv
1       2  2020                       119648  RS_Session_255_AU_749.C.csv

RS_Session_256_AS_154.A.csv:
   Year  Number of Vehicles  Percentage Change WRT Previous Year  \
0  2019              164852                                  NaN
1  2020              123528                               -25.07

                   source_file
0  RS_Session_256_AS_154.A.csv
1  RS_Session_256_AS_154.A.csv

RS_Session_259_AU_2032_A.csv:
   Year  Total Count                   source_file
0  2014         2391  RS_Session_259_AU_2032_A.csv
1  2015         7790  RS_Session_259_AU_2032_A.csv

RS_Session_259_AU_2477_C_and_D.csv:
   Year  Electric Vehicles Registered in a Calendar Year  \
0  2020                                           124026
1  2021                                           329808

   Percentage Increase in registration from the previous year  \
0                                                         NaN
1                                                       165.9

                          source_file
0  RS_Session_259_AU_2477_C_and_D.csv
1  RS_Session_259_AU_2477_C_and_D.csv

RS_Session_260_AU_1872_A_and_B.csv:
   Sl. No. Vehicle Category  2018 - Total  2018 - EV  2018 - %  2019 - Total  \
0        1      Two Wheeler      19576235      17067      0.09      18644700
1        2    Three Wheeler        764806     110133     14.40        765867

   2019 - EV  2019 - %  2020 - Total  2020 - EV  ...  2021 - Total  2021 - EV  \
0      30389      0.16      14305129      29113  ...      13926217     156243
1     133489     17.43        400893      90385  ...        390820     158129

   2021 - %  2022 - Total  2022 - EV  2022 - %  \
0      1.12      15592118     631181      4.05
1     40.46        677034     350247     51.73

   2023 (Till 01-08-2023) - Total  2023 (Till 01-08-2023) - EV  \
0                         9276337                       489637
1                          572654                       300114

   2023 (Till 01-08-2023) - %                         source_file
0                        5.28  RS_Session_260_AU_1872_A_and_B.csv
1                       52.41  RS_Session_260_AU_1872_A_and_B.csv

[2 rows x 21 columns]

RS_Session_263_AU_905_A.csv:
  Calendar Year  Electric Vehicles Registered                  source_file
0          2022                          4178  RS_Session_263_AU_905_A.csv
1          2023                          6312  RS_Session_263_AU_905_A.csv

RS_Session_265_AU_1355_A_and_B.csv:
      Year  Number of Registered Electric Vehicles  \
0  2019-20                                  173604
1  2020-21                                  142383

                          source_file
0  RS_Session_265_AU_1355_A_and_B.csv
1  RS_Session_265_AU_1355_A_and_B.csv

In [5]:
# --- EV Registration Trends: build simple year-level table ---
simple_files = [
    "RS_Session_255_AU_749.C.csv",
    "RS_Session_256_AS_154.A.csv",
    "RS_Session_259_AU_2032_A.csv",
    "RS_Session_259_AU_2477_C_and_D.csv",
    "RS_Session_263_AU_905_A.csv",
    "RS_Session_265_AU_1355_A_and_B.csv",
]

rename_maps = {
    "RS_Session_255_AU_749.C.csv": {"Year": "year", "Number of Electric Vehicles": "ev_count"},
    "RS_Session_256_AS_154.A.csv": {"Year": "year", "Number of Vehicles": "ev_count",
                                     "Percentage Change WRT Previous Year": "pct_change"},
    "RS_Session_259_AU_2032_A.csv": {"Year": "year", "Total Count": "ev_count"},
    "RS_Session_259_AU_2477_C_and_D.csv": {
        "Year": "year",
        "Electric Vehicles Registered in a Calendar Year": "ev_count",
        "Percentage Increase in registration from the previous year": "pct_change"},
    "RS_Session_263_AU_905_A.csv": {"Calendar Year": "year", "Electric Vehicles Registered": "ev_count"},
    "RS_Session_265_AU_1355_A_and_B.csv": {"Year": "year", "Number of Registered Electric Vehicles": "ev_count"},
}

frames = []
for f in simple_files:
    df = load_and_clean(f)
    df = df.rename(columns=rename_maps[f])
    df["source_file"] = f
    df = df[[c for c in ["year", "ev_count", "pct_change", "source_file"] if c in df.columns]]
    frames.append(df)

master_ev_registration_trends = pd.concat(frames, ignore_index=True, sort=False)
master_ev_registration_trends.info()
master_ev_registration_trends

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   year         30 non-null     object
 1   ev_count     30 non-null     int64
 2   source_file  30 non-null     object
 3   pct_change   4 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 1.1+ KB

,year,ev_count,source_file,pct_change
0,2019,161314,RS_Session_255_AU_749.C.csv,NaN
1,2020,119648,RS_Session_255_AU_749.C.csv,NaN
2,Total,280962,RS_Session_255_AU_749.C.csv,NaN
3,2019,164852,RS_Session_256_AS_154.A.csv,NaN
4,2020,123528,RS_Session_256_AS_154.A.csv,-25.07
5,2021,324840,RS_Session_256_AS_154.A.csv,162.97
6,2014,2391,RS_Session_259_AU_2032_A.csv,NaN
7,2015,7790,RS_Session_259_AU_2032_A.csv,NaN
8,2016,49622,RS_Session_259_AU_2032_A.csv,NaN
9,2017,86720,RS_Session_259_AU_2032_A.csv,NaN
10,2018,129125,RS_Session_259_AU_2032_A.csv,NaN
11,2019,165461,RS_Session_259_AU_2032_A.csv,NaN
12,2020,123092,RS_Session_259_AU_2032_A.csv,NaN
13,2021,327976,RS_Session_259_AU_2032_A.csv,NaN
14,2022,1015196,RS_Session_259_AU_2032_A.csv,NaN
15,2023 (till 15-03-2023),256980,RS_Session_259_AU_2032_A.csv,NaN
16,Grand Total,2164353,RS_Session_259_AU_2032_A.csv,NaN
17,2020,124026,RS_Session_259_AU_2477_C_and_D.csv,NaN
18,2021,329808,RS_Session_259_AU_2477_C_and_D.csv,165.90
19,2022,1020679,RS_Session_259_AU_2477_C_and_D.csv,209.40
20,2023 (Till 19-03-2023),278976,RS_Session_259_AU_2477_C_and_D.csv,NaN
21,2022,4178,RS_Session_263_AU_905_A.csv,NaN
22,2023,6312,RS_Session_263_AU_905_A.csv,NaN
23,2024,667,RS_Session_263_AU_905_A.csv,NaN
24,Total,11157,RS_Session_263_AU_905_A.csv,NaN
25,2019-20,173604,RS_Session_265_AU_1355_A_and_B.csv,NaN
26,2020-21,142383,RS_Session_265_AU_1355_A_and_B.csv,NaN
27,2021-22,459058,RS_Session_265_AU_1355_A_and_B.csv,NaN
28,2022-23,1183341,RS_Session_265_AU_1355_A_and_B.csv,NaN
29,2023-24,1681127,RS_Session_265_AU_1355_A_and_B.csv,NaN

In [6]:
master_ev_registration_trends = master_ev_registration_trends[
    ~master_ev_registration_trends["year"].astype(str).str.contains("Total", case=False, na=False)
].reset_index(drop=True)

master_ev_registration_trends.info()
master_ev_registration_trends

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   year         27 non-null     object
 1   ev_count     27 non-null     int64
 2   source_file  27 non-null     object
 3   pct_change   4 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 996.0+ bytes

,year,ev_count,source_file,pct_change
0,2019,161314,RS_Session_255_AU_749.C.csv,NaN
1,2020,119648,RS_Session_255_AU_749.C.csv,NaN
2,2019,164852,RS_Session_256_AS_154.A.csv,NaN
3,2020,123528,RS_Session_256_AS_154.A.csv,-25.07
4,2021,324840,RS_Session_256_AS_154.A.csv,162.97
5,2014,2391,RS_Session_259_AU_2032_A.csv,NaN
6,2015,7790,RS_Session_259_AU_2032_A.csv,NaN
7,2016,49622,RS_Session_259_AU_2032_A.csv,NaN
8,2017,86720,RS_Session_259_AU_2032_A.csv,NaN
9,2018,129125,RS_Session_259_AU_2032_A.csv,NaN
10,2019,165461,RS_Session_259_AU_2032_A.csv,NaN
11,2020,123092,RS_Session_259_AU_2032_A.csv,NaN
12,2021,327976,RS_Session_259_AU_2032_A.csv,NaN
13,2022,1015196,RS_Session_259_AU_2032_A.csv,NaN
14,2023 (till 15-03-2023),256980,RS_Session_259_AU_2032_A.csv,NaN
15,2020,124026,RS_Session_259_AU_2477_C_and_D.csv,NaN
16,2021,329808,RS_Session_259_AU_2477_C_and_D.csv,165.90
17,2022,1020679,RS_Session_259_AU_2477_C_and_D.csv,209.40
18,2023 (Till 19-03-2023),278976,RS_Session_259_AU_2477_C_and_D.csv,NaN
19,2022,4178,RS_Session_263_AU_905_A.csv,NaN
20,2023,6312,RS_Session_263_AU_905_A.csv,NaN
21,2024,667,RS_Session_263_AU_905_A.csv,NaN
22,2019-20,173604,RS_Session_265_AU_1355_A_and_B.csv,NaN
23,2020-21,142383,RS_Session_265_AU_1355_A_and_B.csv,NaN
24,2021-22,459058,RS_Session_265_AU_1355_A_and_B.csv,NaN
25,2022-23,1183341,RS_Session_265_AU_1355_A_and_B.csv,NaN
26,2023-24,1681127,RS_Session_265_AU_1355_A_and_B.csv,NaN

In [7]:
# --- EV Registration Trends: category-wise wide table → long format ---
df_wide = load_and_clean("RS_Session_260_AU_1872_A_and_B.csv")

records = []
years = ["2018", "2019", "2020", "2021", "2022", "2023 (Till 01-08-2023)"]
for _, row in df_wide.iterrows():
    for yr in years:
        records.append({
            "year": yr,
            "vehicle_category": row["Vehicle Category"],
            "total_vehicles": row.get(f"{yr} - Total"),
            "ev_count": row.get(f"{yr} - EV"),
            "ev_pct": row.get(f"{yr} - %"),
            "source_file": "RS_Session_260_AU_1872_A_and_B.csv"
        })

master_ev_registration_by_category = pd.DataFrame(records)
master_ev_registration_by_category.info()
master_ev_registration_by_category

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   year              30 non-null     object
 1   vehicle_category  30 non-null     object
 2   total_vehicles    30 non-null     int64
 3   ev_count          30 non-null     int64
 4   ev_pct            30 non-null     float64
 5   source_file       30 non-null     object
dtypes: float64(1), int64(2), object(3)
memory usage: 1.5+ KB

,year,vehicle_category,total_vehicles,ev_count,ev_pct,source_file
0,2018,Two Wheeler,19576235,17067,0.09,RS_Session_260_AU_1872_A_and_B.csv
1,2019,Two Wheeler,18644700,30389,0.16,RS_Session_260_AU_1872_A_and_B.csv
2,2020,Two Wheeler,14305129,29113,0.20,RS_Session_260_AU_1872_A_and_B.csv
3,2021,Two Wheeler,13926217,156243,1.12,RS_Session_260_AU_1872_A_and_B.csv
4,2022,Two Wheeler,15592118,631181,4.05,RS_Session_260_AU_1872_A_and_B.csv
5,2023 (Till 01-08-2023),Two Wheeler,9276337,489637,5.28,RS_Session_260_AU_1872_A_and_B.csv
6,2018,Three Wheeler,764806,110133,14.40,RS_Session_260_AU_1872_A_and_B.csv
7,2019,Three Wheeler,765867,133489,17.43,RS_Session_260_AU_1872_A_and_B.csv
8,2020,Three Wheeler,400893,90385,22.55,RS_Session_260_AU_1872_A_and_B.csv
9,2021,Three Wheeler,390820,158129,40.46,RS_Session_260_AU_1872_A_and_B.csv
10,2022,Three Wheeler,677034,350247,51.73,RS_Session_260_AU_1872_A_and_B.csv
11,2023 (Till 01-08-2023),Three Wheeler,572654,300114,52.41,RS_Session_260_AU_1872_A_and_B.csv
12,2018,Four Wheeler,2999288,1047,0.03,RS_Session_260_AU_1872_A_and_B.csv
13,2019,Four Wheeler,2822782,962,0.03,RS_Session_260_AU_1872_A_and_B.csv
14,2020,Four Wheeler,2396428,3207,0.13,RS_Session_260_AU_1872_A_and_B.csv
15,2021,Four Wheeler,2945340,12259,0.42,RS_Session_260_AU_1872_A_and_B.csv
16,2022,Four Wheeler,3346973,33205,0.99,RS_Session_260_AU_1872_A_and_B.csv
17,2023 (Till 01-08-2023),Four Wheeler,2020459,40186,1.99,RS_Session_260_AU_1872_A_and_B.csv
18,2018,Goods Vehicles,886047,658,0.07,RS_Session_260_AU_1872_A_and_B.csv
19,2019,Goods Vehicles,799661,54,0.01,RS_Session_260_AU_1872_A_and_B.csv
20,2020,Goods Vehicles,503358,15,0.00,RS_Session_260_AU_1872_A_and_B.csv
21,2021,Goods Vehicles,602805,1118,0.19,RS_Session_260_AU_1872_A_and_B.csv
22,2022,Goods Vehicles,804409,653,0.08,RS_Session_260_AU_1872_A_and_B.csv
23,2023 (Till 01-08-2023),Goods Vehicles,490920,1512,0.31,RS_Session_260_AU_1872_A_and_B.csv
24,2018,Public Service Vehicle,79317,50,0.06,RS_Session_260_AU_1872_A_and_B.csv
25,2019,Public Service Vehicle,81022,508,0.63,RS_Session_260_AU_1872_A_and_B.csv
26,2020,Public Service Vehicle,40328,88,0.22,RS_Session_260_AU_1872_A_and_B.csv
27,2021,Public Service Vehicle,15434,1177,7.63,RS_Session_260_AU_1872_A_and_B.csv
28,2022,Public Service Vehicle,45448,1972,4.34,RS_Session_260_AU_1872_A_and_B.csv
29,2023 (Till 01-08-2023),Public Service Vehicle,47058,985,2.09,RS_Session_260_AU_1872_A_and_B.csv

## Insights: EV Registration Trends

- Overall EV registrations show strong, consistent growth from 2019 onward,
  accelerating sharply from 2021–2022 — one series jumps from ~124,000 (2020)
  to ~1,020,000 (2022), roughly 8x in two years.
- A clear dip appears in 2020 across multiple independent files (e.g. one
  series drops from ~165,000 to ~123,000, -25% YoY) — consistent with
  COVID-19 disrupting vehicle sales broadly that year.
- Category-wise adoption is very uneven, not a single uniform trend:
  - Three-wheelers lead by far — EV share rose from 14.4% (2018) to over
    52% (2023), likely driven by commercial/gig use (e-rickshaws, delivery).
  - Two-wheelers grew from ~0.1% to ~5.3% — real but much slower growth.
  - Four-wheelers (passenger cars) stayed under 2% EV share even by 2023 —
    adoption here is still in a very early stage.
  - Goods vehicles and public service vehicles remain under 1–4%.
- Takeaway: "EV adoption in India" is really a three-wheeler-led transition
  first, with two-wheelers following at a distance, and passenger cars
  barely moving yet.
- Caveat: these are separate government disclosures answering separate
  Parliament questions, not one continuous time series — cross-file
  comparisons (like the 2020 dip) are suggestive, not statistically
  confirmed, until formally joined during EDA.

In [9]:
for f in theme_groups["state_wise_ev_data"]:
    df = load_and_clean(f)
    print(f"\n{f} — shape {df.shape}")
    display(df.head(2))

RS_Session_254_AU_697_1.csv — shape (37, 3)

  Sl. No.          State/UT  Total Number of Invoice/Sales
0       1     Jammu Kashmir                            437
1       2  Himachal Pradesh                            241

RS_Session_255_AU_2349_2.csv — shape (35, 3)

  Sl. No.          State/UT  Total Number of Invoices/Sales
0       1     Jammu Kashmir                            1036
1       2  Himachal Pradesh                             446

RS_Session_256_AU_95_C.csv — shape (33, 11)

,State Name,Two Wheeler,Three Wheeler,Four Wheeler,Goods Vehicles,Public Service Vehicle,Special Category Vehicles,Ambulance/Hearses,Construction Equipment Vehicle,Other,Grand Total
0,Andaman and Nicobar Island,1,30.0,81,NaN,40.0,NaN,NaN,NaN,7.0,159
1,Arunachal Pradesh,14,NaN,5,NaN,NaN,NaN,NaN,NaN,1.0,20

RS_Session_258_AU_429_1.csv — shape (35, 18)

,S.No.,State Name,2WN,2WT,2WIC,3WN,3WT,LMV,LPV,LGV,4WIC,MMV,MPV,MGV,HPV,HGV,OTH,Grand Total
0,1,Andaman and Nicobar Island,2,5.0,NaN,NaN,30.0,86,6.0,NaN,NaN,NaN,NaN,NaN,40.0,NaN,NaN,169
1,2,Andhra Pradesh,27629,NaN,2.0,374.0,108.0,1050,3.0,166.0,NaN,NaN,NaN,NaN,NaN,NaN,1117.0,30449

RS_Session_258_AU_91_1.csv — shape (35, 18)

,Sr. No.,State/UT Name,2WN,2WT,2WIC,3WN,3WT,LMV,LPV,LGV,4WIC,MMV,MPV,MGV,HPV,HGV,OTH,Grand Total
0,1,Andaman and Nicobar Island,2,5.0,NaN,NaN,30.0,86,6.0,NaN,NaN,NaN,NaN,NaN,40.0,NaN,NaN,169
1,2,Andhra Pradesh,27629,NaN,2.0,374.0,108.0,1050,3.0,166.0,NaN,NaN,NaN,NaN,NaN,NaN,1117.0,30449

RS_Session_259_AU_3475_1.csv — shape (35, 3)

  S. No.                  State Name  Electric Vehicle Count
0      1  Andaman and Nicobar Island                     182
1      2              Andhra Pradesh                   51322

RS_Session_260_AU_2349_A_to_B.csv — shape (35, 4)

  Sl.No.                     State/UT  Electric  Non-electric
0      1  Andaman and Nicobar Islands       190        161258
1      2               Andhra Pradesh     67905      16553509

In [10]:
df_429 = load_and_clean("RS_Session_258_AU_429_1.csv")
df_91 = load_and_clean("RS_Session_258_AU_91_1.csv")
print(df_429.drop(columns=["Sl.No." if "Sl.No." in df_429.columns else "S.No."], errors="ignore").equals(
    df_91.drop(columns=["Sr. No."], errors="ignore")
))

False

In [11]:
df_429 = load_and_clean("RS_Session_258_AU_429_1.csv")
df_91 = load_and_clean("RS_Session_258_AU_91_1.csv")

# align state name columns so we can compare row by row
state_col_429 = "State Name"
state_col_91 = "State/UT Name"

df_429_sorted = df_429.sort_values(state_col_429).reset_index(drop=True)
df_91_sorted = df_91.sort_values(state_col_91).reset_index(drop=True)

print("Shapes:", df_429_sorted.shape, df_91_sorted.shape)
print("\nStates in 429 but not in 91:",
      set(df_429_sorted[state_col_429]) - set(df_91_sorted[state_col_91]))
print("States in 91 but not in 429:",
      set(df_91_sorted[state_col_91]) - set(df_429_sorted[state_col_429]))

# compare Grand Total column state by state
compare = df_429_sorted[[state_col_429, "Grand Total"]].merge(
    df_91_sorted[[state_col_91, "Grand Total"]],
    left_on=state_col_429, right_on=state_col_91,
    suffixes=("_429", "_91")
)
compare["diff"] = compare["Grand Total_429"] - compare["Grand Total_91"]
compare[compare["diff"] != 0]

Shapes: (35, 18) (35, 18)

States in 429 but not in 91: set()
States in 91 but not in 429: set()

Empty DataFrame
Columns: [State Name, Grand Total_429, State/UT Name, Grand Total_91, diff]
Index: []

In [22]:
# --- Group 3: vehicle type-code breakdown by state (melt wide -> long) ---
# Note: RS_Session_258_AU_429_1.csv is a duplicate of this file (verified identical
# Grand Totals for all 35 states) — excluded to avoid double-counting.

df_type = load_and_clean("RS_Session_258_AU_91_1.csv")
df_type = df_type[~df_type["State/UT Name"].astype(str).str.contains("Total", case=False, na=False)]

type_cols = [c for c in df_type.columns if c not in
             ["Sr. No.", "State/UT Name", "Grand Total", "source_file"]]

master_state_vehicle_type = df_type.melt(
    id_vars=["State/UT Name"],
    value_vars=type_cols,
    var_name="vehicle_type_code",
    value_name="count"
).rename(columns={"State/UT Name": "state"})
master_state_vehicle_type["source_file"] = "RS_Session_258_AU_91_1.csv"

master_state_vehicle_type.info()
master_state_vehicle_type

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 510 entries, 0 to 509
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   state              510 non-null    object
 1   vehicle_type_code  510 non-null    object
 2   count              276 non-null    float64
 3   source_file        510 non-null    object
dtypes: float64(1), object(3)
memory usage: 16.1+ KB

,state,vehicle_type_code,count,source_file
0,Andaman and Nicobar Island,2WN,2.0,RS_Session_258_AU_91_1.csv
1,Andhra Pradesh,2WN,27629.0,RS_Session_258_AU_91_1.csv
2,Arunachal Pradesh,2WN,14.0,RS_Session_258_AU_91_1.csv
3,Assam,2WN,2287.0,RS_Session_258_AU_91_1.csv
4,Bihar,2WN,13472.0,RS_Session_258_AU_91_1.csv
5,Chandigarh,2WN,1004.0,RS_Session_258_AU_91_1.csv
6,Chhattisgarh,2WN,20112.0,RS_Session_258_AU_91_1.csv
7,Delhi,2WN,43627.0,RS_Session_258_AU_91_1.csv
8,Goa,2WN,5555.0,RS_Session_258_AU_91_1.csv
9,Gujarat,2WN,67990.0,RS_Session_258_AU_91_1.csv
10,Haryana,2WN,17935.0,RS_Session_258_AU_91_1.csv
11,Himachal Pradesh,2WN,1190.0,RS_Session_258_AU_91_1.csv
12,Jammu and Kashmir,2WN,3294.0,RS_Session_258_AU_91_1.csv
13,Jharkhand,2WN,8744.0,RS_Session_258_AU_91_1.csv
14,Karnataka,2WN,121733.0,RS_Session_258_AU_91_1.csv
15,Kerala,2WN,38019.0,RS_Session_258_AU_91_1.csv
16,Ladakh,2WN,26.0,RS_Session_258_AU_91_1.csv
17,Madhya Pradesh,2WN,11623.0,RS_Session_258_AU_91_1.csv
18,Maharashtra,2WN,149977.0,RS_Session_258_AU_91_1.csv
19,Manipur,2WN,143.0,RS_Session_258_AU_91_1.csv
20,Meghalaya,2WN,35.0,RS_Session_258_AU_91_1.csv
21,Mizoram,2WN,34.0,RS_Session_258_AU_91_1.csv
22,Nagaland,2WN,50.0,RS_Session_258_AU_91_1.csv
23,Odisha,2WN,32223.0,RS_Session_258_AU_91_1.csv
24,Puducherry,2WN,2569.0,RS_Session_258_AU_91_1.csv
25,Punjab,2WN,12784.0,RS_Session_258_AU_91_1.csv
26,Rajasthan,2WN,69685.0,RS_Session_258_AU_91_1.csv
27,Sikkim,2WN,1.0,RS_Session_258_AU_91_1.csv
28,Tamil Nadu,2WN,96601.0,RS_Session_258_AU_91_1.csv
29,Tripura,2WN,196.0,RS_Session_258_AU_91_1.csv
30,Dadra and Nagar Haveli and Daman and Diu,2WN,126.0,RS_Session_258_AU_91_1.csv
31,Uttar Pradesh,2WN,38043.0,RS_Session_258_AU_91_1.csv
32,Uttarakhand,2WN,7537.0,RS_Session_258_AU_91_1.csv
33,West Bengal,2WN,9515.0,RS_Session_258_AU_91_1.csv
34,Andaman and Nicobar Island,2WT,5.0,RS_Session_258_AU_91_1.csv
35,Andhra Pradesh,2WT,NaN,RS_Session_258_AU_91_1.csv
36,Arunachal Pradesh,2WT,NaN,RS_Session_258_AU_91_1.csv
37,Assam,2WT,NaN,RS_Session_258_AU_91_1.csv
38,Bihar,2WT,NaN,RS_Session_258_AU_91_1.csv
39,Chandigarh,2WT,NaN,RS_Session_258_AU_91_1.csv
40,Chhattisgarh,2WT,NaN,RS_Session_258_AU_91_1.csv
41,Delhi,2WT,NaN,RS_Session_258_AU_91_1.csv
42,Goa,2WT,1.0,RS_Session_258_AU_91_1.csv
43,Gujarat,2WT,NaN,RS_Session_258_AU_91_1.csv
44,Haryana,2WT,53.0,RS_Session_258_AU_91_1.csv
45,Himachal Pradesh,2WT,NaN,RS_Session_258_AU_91_1.csv
46,Jammu and Kashmir,2WT,NaN,RS_Session_258_AU_91_1.csv
47,Jharkhand,2WT,NaN,RS_Session_258_AU_91_1.csv
48,Karnataka,2WT,9395.0,RS_Session_258_AU_91_1.csv
49,Kerala,2WT,35.0,RS_Session_258_AU_91_1.csv
50,Ladakh,2WT,NaN,RS_Session_258_AU_91_1.csv
51,Madhya Pradesh,2WT,NaN,RS_Session_258_AU_91_1.csv
52,Maharashtra,2WT,5.0,RS_Session_258_AU_91_1.csv
53,Manipur,2WT,NaN,RS_Session_258_AU_91_1.csv
54,Meghalaya,2WT,NaN,RS_Session_258_AU_91_1.csv
55,Mizoram,2WT,NaN,RS_Session_258_AU_91_1.csv
56,Nagaland,2WT,NaN,RS_Session_258_AU_91_1.csv
57,Odisha,2WT,7.0,RS_Session_258_AU_91_1.csv
58,Puducherry,2WT,NaN,RS_Session_258_AU_91_1.csv
59,Punjab,2WT,NaN,RS_Session_258_AU_91_1.csv
60,Rajasthan,2WT,70.0,RS_Session_258_AU_91_1.csv
61,Sikkim,2WT,NaN,RS_Session_258_AU_91_1.csv
62,Tamil Nadu,2WT,NaN,RS_Session_258_AU_91_1.csv
63,Tripura,2WT,NaN,RS_Session_258_AU_91_1.csv
64,Dadra and Nagar Haveli and Daman and Diu,2WT,NaN,RS_Session_258_AU_91_1.csv
65,Uttar Pradesh,2WT,20.0,RS_Session_258_AU_91_1.csv
66,Uttarakhand,2WT,7.0,RS_Session_258_AU_91_1.csv
67,West Bengal,2WT,NaN,RS_Session_258_AU_91_1.csv
68,Andaman and Nicobar Island,2WIC,NaN,RS_Session_258_AU_91_1.csv
69,Andhra Pradesh,2WIC,2.0,RS_Session_258_AU_91_1.csv
70,Arunachal Pradesh,2WIC,NaN,RS_Session_258_AU_91_1.csv
71,Assam,2WIC,NaN,RS_Session_258_AU_91_1.csv
72,Bihar,2WIC,NaN,RS_Session_258_AU_91_1.csv
73,Chandigarh,2WIC,NaN,RS_Session_258_AU_91_1.csv
74,Chhattisgarh,2WIC,NaN,RS_Session_258_AU_91_1.csv
75,Delhi,2WIC,2.0,RS_Session_258_AU_91_1.csv
76,Goa,2WIC,NaN,RS_Session_258_AU_91_1.csv
77,Gujarat,2WIC,3.0,RS_Session_258_AU_91_1.csv
78,Haryana,2WIC,NaN,RS_Session_258_AU_91_1.csv
79,Himachal Pradesh,2WIC,NaN,RS_Session_258_AU_91_1.csv
80,Jammu and Kashmir,2WIC,NaN,RS_Session_258_AU_91_1.csv
81,Jharkhand,2WIC,NaN,RS_Session_258_AU_91_1.csv
82,Karnataka,2WIC,7.0,RS_Session_258_AU_91_1.csv
83,Kerala,2WIC,32.0,RS_Session_258_AU_91_1.csv
84,Ladakh,2WIC,NaN,RS_Session_258_AU_91_1.csv
85,Madhya Pradesh,2WIC,NaN,RS_Session_258_AU_91_1.csv
86,Maharashtra,2WIC,4.0,RS_Session_258_AU_91_1.csv
87,Manipur,2WIC,NaN,RS_Session_258_AU_91_1.csv
88,Meghalaya,2WIC,NaN,RS_Session_258_AU_91_1.csv
89,Mizoram,2WIC,NaN,RS_Session_258_AU_91_1.csv
90,Nagaland,2WIC,NaN,RS_Session_258_AU_91_1.csv
91,Odisha,2WIC,1.0,RS_Session_258_AU_91_1.csv
92,Puducherry,2WIC,NaN,RS_Session_258_AU_91_1.csv
93,Punjab,2WIC,NaN,RS_Session_258_AU_91_1.csv
94,Rajasthan,2WIC,4.0,RS_Session_258_AU_91_1.csv
95,Sikkim,2WIC,NaN,RS_Session_258_AU_91_1.csv
96,Tamil Nadu,2WIC,2.0,RS_Session_258_AU_91_1.csv
97,Tripura,2WIC,NaN,RS_Session_258_AU_91_1.csv
98,Dadra and Nagar Haveli and Daman and Diu,2WIC,NaN,RS_Session_258_AU_91_1.csv
99,Uttar Pradesh,2WIC,1.0,RS_Session_258_AU_91_1.csv
100,Uttarakhand,2WIC,NaN,RS_Session_258_AU_91_1.csv
101,West Bengal,2WIC,NaN,RS_Session_258_AU_91_1.csv
102,Andaman and Nicobar Island,3WN,NaN,RS_Session_258_AU_91_1.csv
103,Andhra Pradesh,3WN,374.0,RS_Session_258_AU_91_1.csv
104,Arunachal Pradesh,3WN,NaN,RS_Session_258_AU_91_1.csv
105,Assam,3WN,NaN,RS_Session_258_AU_91_1.csv
106,Bihar,3WN,2.0,RS_Session_258_AU_91_1.csv
107,Chandigarh,3WN,NaN,RS_Session_258_AU_91_1.csv
108,Chhattisgarh,3WN,130.0,RS_Session_258_AU_91_1.csv
109,Delhi,3WN,NaN,RS_Session_258_AU_91_1.csv
110,Goa,3WN,4.0,RS_Session_258_AU_91_1.csv
111,Gujarat,3WN,32.0,RS_Session_258_AU_91_1.csv
112,Haryana,3WN,NaN,RS_Session_258_AU_91_1.csv
113,Himachal Pradesh,3WN,1.0,RS_Session_258_AU_91_1.csv
114,Jammu and Kashmir,3WN,NaN,RS_Session_258_AU_91_1.csv
115,Jharkhand,3WN,NaN,RS_Session_258_AU_91_1.csv
116,Karnataka,3WN,30.0,RS_Session_258_AU_91_1.csv
117,Kerala,3WN,78.0,RS_Session_258_AU_91_1.csv
118,Ladakh,3WN,NaN,RS_Session_258_AU_91_1.csv
119,Madhya Pradesh,3WN,NaN,RS_Session_258_AU_91_1.csv
120,Maharashtra,3WN,37.0,RS_Session_258_AU_91_1.csv
121,Manipur,3WN,NaN,RS_Session_258_AU_91_1.csv
122,Meghalaya,3WN,7.0,RS_Session_258_AU_91_1.csv
123,Mizoram,3WN,NaN,RS_Session_258_AU_91_1.csv
124,Nagaland,3WN,NaN,RS_Session_258_AU_91_1.csv
125,Odisha,3WN,2.0,RS_Session_258_AU_91_1.csv
126,Puducherry,3WN,4.0,RS_Session_258_AU_91_1.csv
127,Punjab,3WN,1.0,RS_Session_258_AU_91_1.csv
128,Rajasthan,3WN,NaN,RS_Session_258_AU_91_1.csv
129,Sikkim,3WN,NaN,RS_Session_258_AU_91_1.csv
130,Tamil Nadu,3WN,41.0,RS_Session_258_AU_91_1.csv
131,Tripura,3WN,NaN,RS_Session_258_AU_91_1.csv
132,Dadra and Nagar Haveli and Daman and Diu,3WN,NaN,RS_Session_258_AU_91_1.csv
133,Uttar Pradesh,3WN,1.0,RS_Session_258_AU_91_1.csv
134,Uttarakhand,3WN,NaN,RS_Session_258_AU_91_1.csv
135,West Bengal,3WN,NaN,RS_Session_258_AU_91_1.csv
136,Andaman and Nicobar Island,3WT,30.0,RS_Session_258_AU_91_1.csv
137,Andhra Pradesh,3WT,108.0,RS_Session_258_AU_91_1.csv
138,Arunachal Pradesh,3WT,NaN,RS_Session_258_AU_91_1.csv
139,Assam,3WT,79661.0,RS_Session_258_AU_91_1.csv
140,Bihar,3WT,96560.0,RS_Session_258_AU_91_1.csv
141,Chandigarh,3WT,2683.0,RS_Session_258_AU_91_1.csv
142,Chhattisgarh,3WT,9865.0,RS_Session_258_AU_91_1.csv
143,Delhi,3WT,130429.0,RS_Session_258_AU_91_1.csv
144,Goa,3WT,55.0,RS_Session_258_AU_91_1.csv
145,Gujarat,3WT,2964.0,RS_Session_258_AU_91_1.csv
146,Haryana,3WT,29699.0,RS_Session_258_AU_91_1.csv
147,Himachal Pradesh,3WT,183.0,RS_Session_258_AU_91_1.csv
148,Jammu and Kashmir,3WT,2148.0,RS_Session_258_AU_91_1.csv
149,Jharkhand,3WT,14407.0,RS_Session_258_AU_91_1.csv
150,Karnataka,3WT,7105.0,RS_Session_258_AU_91_1.csv
151,Kerala,3WT,4008.0,RS_Session_258_AU_91_1.csv
152,Ladakh,3WT,NaN,RS_Session_258_AU_91_1.csv
153,Madhya Pradesh,3WT,NaN,RS_Session_258_AU_91_1.csv
154,Maharashtra,3WT,11334.0,RS_Session_258_AU_91_1.csv
155,Manipur,3WT,610.0,RS_Session_258_AU_91_1.csv
156,Meghalaya,3WT,7.0,RS_Session_258_AU_91_1.csv
157,Mizoram,3WT,1.0,RS_Session_258_AU_91_1.csv
158,Nagaland,3WT,NaN,RS_Session_258_AU_91_1.csv
159,Odisha,3WT,3638.0,RS_Session_258_AU_91_1.csv
160,Puducherry,3WT,49.0,RS_Session_258_AU_91_1.csv
161,Punjab,3WT,8101.0,RS_Session_258_AU_91_1.csv
162,Rajasthan,3WT,48898.0,RS_Session_258_AU_91_1.csv
163,Sikkim,3WT,NaN,RS_Session_258_AU_91_1.csv
164,Tamil Nadu,3WT,6885.0,RS_Session_258_AU_91_1.csv
165,Tripura,3WT,10708.0,RS_Session_258_AU_91_1.csv
166,Dadra and Nagar Haveli and Daman and Diu,3WT,56.0,RS_Session_258_AU_91_1.csv
167,Uttar Pradesh,3WT,375595.0,RS_Session_258_AU_91_1.csv
168,Uttarakhand,3WT,30122.0,RS_Session_258_AU_91_1.csv
169,West Bengal,3WT,42372.0,RS_Session_258_AU_91_1.csv
170,Andaman and Nicobar Island,LMV,86.0,RS_Session_258_AU_91_1.csv
171,Andhra Pradesh,LMV,1050.0,RS_Session_258_AU_91_1.csv
172,Arunachal Pradesh,LMV,6.0,RS_Session_258_AU_91_1.csv
173,Assam,LMV,233.0,RS_Session_258_AU_91_1.csv
174,Bihar,LMV,231.0,RS_Session_258_AU_91_1.csv
175,Chandigarh,LMV,391.0,RS_Session_258_AU_91_1.csv
176,Chhattisgarh,LMV,396.0,RS_Session_258_AU_91_1.csv
177,Delhi,LMV,5796.0,RS_Session_258_AU_91_1.csv
178,Goa,LMV,861.0,RS_Session_258_AU_91_1.csv
179,Gujarat,LMV,3926.0,RS_Session_258_AU_91_1.csv
180,Haryana,LMV,425.0,RS_Session_258_AU_91_1.csv
181,Himachal Pradesh,LMV,69.0,RS_Session_258_AU_91_1.csv
182,Jammu and Kashmir,LMV,55.0,RS_Session_258_AU_91_1.csv
183,Jharkhand,LMV,212.0,RS_Session_258_AU_91_1.csv
184,Karnataka,LMV,9265.0,RS_Session_258_AU_91_1.csv
185,Kerala,LMV,5746.0,RS_Session_258_AU_91_1.csv
186,Ladakh,LMV,10.0,RS_Session_258_AU_91_1.csv
187,Madhya Pradesh,LMV,169.0,RS_Session_258_AU_91_1.csv
188,Maharashtra,LMV,15583.0,RS_Session_258_AU_91_1.csv
189,Manipur,LMV,4.0,RS_Session_258_AU_91_1.csv
190,Meghalaya,LMV,20.0,RS_Session_258_AU_91_1.csv
191,Mizoram,LMV,3.0,RS_Session_258_AU_91_1.csv
192,Nagaland,LMV,6.0,RS_Session_258_AU_91_1.csv
193,Odisha,LMV,468.0,RS_Session_258_AU_91_1.csv
194,Puducherry,LMV,97.0,RS_Session_258_AU_91_1.csv
195,Punjab,LMV,148.0,RS_Session_258_AU_91_1.csv
196,Rajasthan,LMV,2026.0,RS_Session_258_AU_91_1.csv
197,Sikkim,LMV,10.0,RS_Session_258_AU_91_1.csv
198,Tamil Nadu,LMV,4101.0,RS_Session_258_AU_91_1.csv
199,Tripura,LMV,11.0,RS_Session_258_AU_91_1.csv
200,Dadra and Nagar Haveli and Daman and Diu,LMV,31.0,RS_Session_258_AU_91_1.csv
201,Uttar Pradesh,LMV,518.0,RS_Session_258_AU_91_1.csv
202,Uttarakhand,LMV,469.0,RS_Session_258_AU_91_1.csv
203,West Bengal,LMV,1305.0,RS_Session_258_AU_91_1.csv
204,Andaman and Nicobar Island,LPV,6.0,RS_Session_258_AU_91_1.csv
205,Andhra Pradesh,LPV,3.0,RS_Session_258_AU_91_1.csv
206,Arunachal Pradesh,LPV,1.0,RS_Session_258_AU_91_1.csv
207,Assam,LPV,5.0,RS_Session_258_AU_91_1.csv
208,Bihar,LPV,8.0,RS_Session_258_AU_91_1.csv
209,Chandigarh,LPV,2.0,RS_Session_258_AU_91_1.csv
210,Chhattisgarh,LPV,44.0,RS_Session_258_AU_91_1.csv
211,Delhi,LPV,3415.0,RS_Session_258_AU_91_1.csv
212,Goa,LPV,4.0,RS_Session_258_AU_91_1.csv
213,Gujarat,LPV,91.0,RS_Session_258_AU_91_1.csv
214,Haryana,LPV,478.0,RS_Session_258_AU_91_1.csv
215,Himachal Pradesh,LPV,56.0,RS_Session_258_AU_91_1.csv
216,Jammu and Kashmir,LPV,9.0,RS_Session_258_AU_91_1.csv
217,Jharkhand,LPV,99.0,RS_Session_258_AU_91_1.csv
218,Karnataka,LPV,2160.0,RS_Session_258_AU_91_1.csv
219,Kerala,LPV,47.0,RS_Session_258_AU_91_1.csv
220,Ladakh,LPV,NaN,RS_Session_258_AU_91_1.csv
221,Madhya Pradesh,LPV,NaN,RS_Session_258_AU_91_1.csv
222,Maharashtra,LPV,954.0,RS_Session_258_AU_91_1.csv
223,Manipur,LPV,1.0,RS_Session_258_AU_91_1.csv
224,Meghalaya,LPV,NaN,RS_Session_258_AU_91_1.csv
225,Mizoram,LPV,4.0,RS_Session_258_AU_91_1.csv
226,Nagaland,LPV,1.0,RS_Session_258_AU_91_1.csv
227,Odisha,LPV,44.0,RS_Session_258_AU_91_1.csv
228,Puducherry,LPV,36.0,RS_Session_258_AU_91_1.csv
229,Punjab,LPV,18.0,RS_Session_258_AU_91_1.csv
230,Rajasthan,LPV,58.0,RS_Session_258_AU_91_1.csv
231,Sikkim,LPV,9.0,RS_Session_258_AU_91_1.csv
232,Tamil Nadu,LPV,203.0,RS_Session_258_AU_91_1.csv
233,Tripura,LPV,1.0,RS_Session_258_AU_91_1.csv
234,Dadra and Nagar Haveli and Daman and Diu,LPV,1.0,RS_Session_258_AU_91_1.csv
235,Uttar Pradesh,LPV,34.0,RS_Session_258_AU_91_1.csv
236,Uttarakhand,LPV,36.0,RS_Session_258_AU_91_1.csv
237,West Bengal,LPV,188.0,RS_Session_258_AU_91_1.csv
238,Andaman and Nicobar Island,LGV,NaN,RS_Session_258_AU_91_1.csv
239,Andhra Pradesh,LGV,166.0,RS_Session_258_AU_91_1.csv
240,Arunachal Pradesh,LGV,NaN,RS_Session_258_AU_91_1.csv
241,Assam,LGV,15.0,RS_Session_258_AU_91_1.csv
242,Bihar,LGV,21.0,RS_Session_258_AU_91_1.csv
243,Chandigarh,LGV,NaN,RS_Session_258_AU_91_1.csv
244,Chhattisgarh,LGV,1070.0,RS_Session_258_AU_91_1.csv
245,Delhi,LGV,50.0,RS_Session_258_AU_91_1.csv
246,Goa,LGV,25.0,RS_Session_258_AU_91_1.csv
247,Gujarat,LGV,51.0,RS_Session_258_AU_91_1.csv
248,Haryana,LGV,118.0,RS_Session_258_AU_91_1.csv
249,Himachal Pradesh,LGV,2.0,RS_Session_258_AU_91_1.csv
250,Jammu and Kashmir,LGV,4.0,RS_Session_258_AU_91_1.csv
251,Jharkhand,LGV,11.0,RS_Session_258_AU_91_1.csv
252,Karnataka,LGV,103.0,RS_Session_258_AU_91_1.csv
253,Kerala,LGV,37.0,RS_Session_258_AU_91_1.csv
254,Ladakh,LGV,NaN,RS_Session_258_AU_91_1.csv
255,Madhya Pradesh,LGV,NaN,RS_Session_258_AU_91_1.csv
256,Maharashtra,LGV,49.0,RS_Session_258_AU_91_1.csv
257,Manipur,LGV,NaN,RS_Session_258_AU_91_1.csv
258,Meghalaya,LGV,2.0,RS_Session_258_AU_91_1.csv
259,Mizoram,LGV,NaN,RS_Session_258_AU_91_1.csv
260,Nagaland,LGV,NaN,RS_Session_258_AU_91_1.csv
261,Odisha,LGV,35.0,RS_Session_258_AU_91_1.csv
262,Puducherry,LGV,9.0,RS_Session_258_AU_91_1.csv
263,Punjab,LGV,34.0,RS_Session_258_AU_91_1.csv
264,Rajasthan,LGV,19.0,RS_Session_258_AU_91_1.csv
265,Sikkim,LGV,NaN,RS_Session_258_AU_91_1.csv
266,Tamil Nadu,LGV,1406.0,RS_Session_258_AU_91_1.csv
267,Tripura,LGV,8.0,RS_Session_258_AU_91_1.csv
268,Dadra and Nagar Haveli and Daman and Diu,LGV,2.0,RS_Session_258_AU_91_1.csv
269,Uttar Pradesh,LGV,81.0,RS_Session_258_AU_91_1.csv
270,Uttarakhand,LGV,1.0,RS_Session_258_AU_91_1.csv
271,West Bengal,LGV,20.0,RS_Session_258_AU_91_1.csv
272,Andaman and Nicobar Island,4WIC,NaN,RS_Session_258_AU_91_1.csv
273,Andhra Pradesh,4WIC,NaN,RS_Session_258_AU_91_1.csv
274,Arunachal Pradesh,4WIC,NaN,RS_Session_258_AU_91_1.csv
275,Assam,4WIC,NaN,RS_Session_258_AU_91_1.csv
276,Bihar,4WIC,1.0,RS_Session_258_AU_91_1.csv
277,Chandigarh,4WIC,NaN,RS_Session_258_AU_91_1.csv
278,Chhattisgarh,4WIC,NaN,RS_Session_258_AU_91_1.csv
279,Delhi,4WIC,4.0,RS_Session_258_AU_91_1.csv
280,Goa,4WIC,NaN,RS_Session_258_AU_91_1.csv
281,Gujarat,4WIC,6.0,RS_Session_258_AU_91_1.csv
282,Haryana,4WIC,NaN,RS_Session_258_AU_91_1.csv
283,Himachal Pradesh,4WIC,NaN,RS_Session_258_AU_91_1.csv
284,Jammu and Kashmir,4WIC,NaN,RS_Session_258_AU_91_1.csv
285,Jharkhand,4WIC,NaN,RS_Session_258_AU_91_1.csv
286,Karnataka,4WIC,1.0,RS_Session_258_AU_91_1.csv
287,Kerala,4WIC,2.0,RS_Session_258_AU_91_1.csv
288,Ladakh,4WIC,NaN,RS_Session_258_AU_91_1.csv
289,Madhya Pradesh,4WIC,NaN,RS_Session_258_AU_91_1.csv
290,Maharashtra,4WIC,1.0,RS_Session_258_AU_91_1.csv
291,Manipur,4WIC,NaN,RS_Session_258_AU_91_1.csv
292,Meghalaya,4WIC,NaN,RS_Session_258_AU_91_1.csv
293,Mizoram,4WIC,NaN,RS_Session_258_AU_91_1.csv
294,Nagaland,4WIC,NaN,RS_Session_258_AU_91_1.csv
295,Odisha,4WIC,NaN,RS_Session_258_AU_91_1.csv
296,Puducherry,4WIC,NaN,RS_Session_258_AU_91_1.csv
297,Punjab,4WIC,NaN,RS_Session_258_AU_91_1.csv
298,Rajasthan,4WIC,NaN,RS_Session_258_AU_91_1.csv
299,Sikkim,4WIC,NaN,RS_Session_258_AU_91_1.csv
300,Tamil Nadu,4WIC,NaN,RS_Session_258_AU_91_1.csv
301,Tripura,4WIC,NaN,RS_Session_258_AU_91_1.csv
302,Dadra and Nagar Haveli and Daman and Diu,4WIC,NaN,RS_Session_258_AU_91_1.csv
303,Uttar Pradesh,4WIC,NaN,RS_Session_258_AU_91_1.csv
304,Uttarakhand,4WIC,NaN,RS_Session_258_AU_91_1.csv
305,West Bengal,4WIC,1.0,RS_Session_258_AU_91_1.csv
306,Andaman and Nicobar Island,MMV,NaN,RS_Session_258_AU_91_1.csv
307,Andhra Pradesh,MMV,NaN,RS_Session_258_AU_91_1.csv
308,Arunachal Pradesh,MMV,NaN,RS_Session_258_AU_91_1.csv
309,Assam,MMV,NaN,RS_Session_258_AU_91_1.csv
310,Bihar,MMV,NaN,RS_Session_258_AU_91_1.csv
311,Chandigarh,MMV,NaN,RS_Session_258_AU_91_1.csv
312,Chhattisgarh,MMV,NaN,RS_Session_258_AU_91_1.csv
313,Delhi,MMV,NaN,RS_Session_258_AU_91_1.csv
314,Goa,MMV,NaN,RS_Session_258_AU_91_1.csv
315,Gujarat,MMV,2.0,RS_Session_258_AU_91_1.csv
316,Haryana,MMV,NaN,RS_Session_258_AU_91_1.csv
317,Himachal Pradesh,MMV,NaN,RS_Session_258_AU_91_1.csv
318,Jammu and Kashmir,MMV,NaN,RS_Session_258_AU_91_1.csv
319,Jharkhand,MMV,NaN,RS_Session_258_AU_91_1.csv
320,Karnataka,MMV,NaN,RS_Session_258_AU_91_1.csv
321,Kerala,MMV,NaN,RS_Session_258_AU_91_1.csv
322,Ladakh,MMV,NaN,RS_Session_258_AU_91_1.csv
323,Madhya Pradesh,MMV,NaN,RS_Session_258_AU_91_1.csv
324,Maharashtra,MMV,4.0,RS_Session_258_AU_91_1.csv
325,Manipur,MMV,NaN,RS_Session_258_AU_91_1.csv
326,Meghalaya,MMV,NaN,RS_Session_258_AU_91_1.csv
327,Mizoram,MMV,NaN,RS_Session_258_AU_91_1.csv
328,Nagaland,MMV,NaN,RS_Session_258_AU_91_1.csv
329,Odisha,MMV,NaN,RS_Session_258_AU_91_1.csv
330,Puducherry,MMV,NaN,RS_Session_258_AU_91_1.csv
331,Punjab,MMV,NaN,RS_Session_258_AU_91_1.csv
332,Rajasthan,MMV,NaN,RS_Session_258_AU_91_1.csv
333,Sikkim,MMV,NaN,RS_Session_258_AU_91_1.csv
334,Tamil Nadu,MMV,NaN,RS_Session_258_AU_91_1.csv
335,Tripura,MMV,NaN,RS_Session_258_AU_91_1.csv
336,Dadra and Nagar Haveli and Daman and Diu,MMV,NaN,RS_Session_258_AU_91_1.csv
337,Uttar Pradesh,MMV,NaN,RS_Session_258_AU_91_1.csv
338,Uttarakhand,MMV,NaN,RS_Session_258_AU_91_1.csv
339,West Bengal,MMV,NaN,RS_Session_258_AU_91_1.csv
340,Andaman and Nicobar Island,MPV,NaN,RS_Session_258_AU_91_1.csv
341,Andhra Pradesh,MPV,NaN,RS_Session_258_AU_91_1.csv
342,Arunachal Pradesh,MPV,NaN,RS_Session_258_AU_91_1.csv
343,Assam,MPV,NaN,RS_Session_258_AU_91_1.csv
344,Bihar,MPV,NaN,RS_Session_258_AU_91_1.csv
345,Chandigarh,MPV,7.0,RS_Session_258_AU_91_1.csv
346,Chhattisgarh,MPV,1.0,RS_Session_258_AU_91_1.csv
347,Delhi,MPV,2.0,RS_Session_258_AU_91_1.csv
348,Goa,MPV,NaN,RS_Session_258_AU_91_1.csv
349,Gujarat,MPV,60.0,RS_Session_258_AU_91_1.csv
350,Haryana,MPV,2.0,RS_Session_258_AU_91_1.csv
351,Himachal Pradesh,MPV,2.0,RS_Session_258_AU_91_1.csv
352,Jammu and Kashmir,MPV,2.0,RS_Session_258_AU_91_1.csv
353,Jharkhand,MPV,NaN,RS_Session_258_AU_91_1.csv
354,Karnataka,MPV,NaN,RS_Session_258_AU_91_1.csv
355,Kerala,MPV,1.0,RS_Session_258_AU_91_1.csv
356,Ladakh,MPV,NaN,RS_Session_258_AU_91_1.csv
357,Madhya Pradesh,MPV,NaN,RS_Session_258_AU_91_1.csv
358,Maharashtra,MPV,242.0,RS_Session_258_AU_91_1.csv
359,Manipur,MPV,NaN,RS_Session_258_AU_91_1.csv
360,Meghalaya,MPV,NaN,RS_Session_258_AU_91_1.csv
361,Mizoram,MPV,NaN,RS_Session_258_AU_91_1.csv
362,Nagaland,MPV,NaN,RS_Session_258_AU_91_1.csv
363,Odisha,MPV,NaN,RS_Session_258_AU_91_1.csv
364,Puducherry,MPV,NaN,RS_Session_258_AU_91_1.csv
365,Punjab,MPV,1.0,RS_Session_258_AU_91_1.csv
366,Rajasthan,MPV,NaN,RS_Session_258_AU_91_1.csv
367,Sikkim,MPV,NaN,RS_Session_258_AU_91_1.csv
368,Tamil Nadu,MPV,NaN,RS_Session_258_AU_91_1.csv
369,Tripura,MPV,NaN,RS_Session_258_AU_91_1.csv
370,Dadra and Nagar Haveli and Daman and Diu,MPV,NaN,RS_Session_258_AU_91_1.csv
371,Uttar Pradesh,MPV,51.0,RS_Session_258_AU_91_1.csv
372,Uttarakhand,MPV,1.0,RS_Session_258_AU_91_1.csv
373,West Bengal,MPV,49.0,RS_Session_258_AU_91_1.csv
374,Andaman and Nicobar Island,MGV,NaN,RS_Session_258_AU_91_1.csv
375,Andhra Pradesh,MGV,NaN,RS_Session_258_AU_91_1.csv
376,Arunachal Pradesh,MGV,NaN,RS_Session_258_AU_91_1.csv
377,Assam,MGV,NaN,RS_Session_258_AU_91_1.csv
378,Bihar,MGV,1.0,RS_Session_258_AU_91_1.csv
379,Chandigarh,MGV,NaN,RS_Session_258_AU_91_1.csv
380,Chhattisgarh,MGV,NaN,RS_Session_258_AU_91_1.csv
381,Delhi,MGV,NaN,RS_Session_258_AU_91_1.csv
382,Goa,MGV,NaN,RS_Session_258_AU_91_1.csv
383,Gujarat,MGV,6.0,RS_Session_258_AU_91_1.csv
384,Haryana,MGV,NaN,RS_Session_258_AU_91_1.csv
385,Himachal Pradesh,MGV,1.0,RS_Session_258_AU_91_1.csv
386,Jammu and Kashmir,MGV,NaN,RS_Session_258_AU_91_1.csv
387,Jharkhand,MGV,NaN,RS_Session_258_AU_91_1.csv
388,Karnataka,MGV,4.0,RS_Session_258_AU_91_1.csv

In [21]:
group1_files = {
    "RS_Session_254_AU_697_1.csv": "Total Number of Invoice/Sales",
    "RS_Session_255_AU_2349_2.csv": "Total Number of Invoices/Sales",
    "RS_Session_259_AU_3475_1.csv": "Electric Vehicle Count",
}

frames = []
for f, value_col in group1_files.items():
    df = load_and_clean(f)
    state_col = "State/UT" if "State/UT" in df.columns else "State Name"
    df = df.rename(columns={state_col: "state", value_col: "count"})
    df["metric"] = value_col
    df["source_file"] = f
    df = df[["state", "count", "metric", "source_file"]]
    frames.append(df)

master_state_simple_counts = pd.concat(frames, ignore_index=True)
master_state_simple_counts = master_state_simple_counts[
    ~master_state_simple_counts["state"].astype(str).str.contains("Total", case=False, na=False)
].reset_index(drop=True)

master_state_simple_counts.info()
master_state_simple_counts

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   state        104 non-null    object
 1   count        104 non-null    int64
 2   metric       104 non-null    object
 3   source_file  104 non-null    object
dtypes: int64(1), object(3)
memory usage: 3.4+ KB

,state,count,metric,source_file
0,Jammu Kashmir,437,Total Number of Invoice/Sales,RS_Session_254_AU_697_1.csv
1,Himachal Pradesh,241,Total Number of Invoice/Sales,RS_Session_254_AU_697_1.csv
2,Punjab,764,Total Number of Invoice/Sales,RS_Session_254_AU_697_1.csv
3,Chandigarh,48,Total Number of Invoice/Sales,RS_Session_254_AU_697_1.csv
4,Uttarakhand,1057,Total Number of Invoice/Sales,RS_Session_254_AU_697_1.csv
5,Haryana,1477,Total Number of Invoice/Sales,RS_Session_254_AU_697_1.csv
6,Delhi,6413,Total Number of Invoice/Sales,RS_Session_254_AU_697_1.csv
7,Rajasthan,6721,Total Number of Invoice/Sales,RS_Session_254_AU_697_1.csv
8,Uttar Pradesh,6022,Total Number of Invoice/Sales,RS_Session_254_AU_697_1.csv
9,Bihar,2615,Total Number of Invoice/Sales,RS_Session_254_AU_697_1.csv
10,Sikkim,0,Total Number of Invoice/Sales,RS_Session_254_AU_697_1.csv
11,Arunachal Pradesh,0,Total Number of Invoice/Sales,RS_Session_254_AU_697_1.csv
12,Nagaland,0,Total Number of Invoice/Sales,RS_Session_254_AU_697_1.csv
13,Manipur,78,Total Number of Invoice/Sales,RS_Session_254_AU_697_1.csv
14,Mizoram,0,Total Number of Invoice/Sales,RS_Session_254_AU_697_1.csv
15,Tripura,538,Total Number of Invoice/Sales,RS_Session_254_AU_697_1.csv
16,Meghalaya,6,Total Number of Invoice/Sales,RS_Session_254_AU_697_1.csv
17,Assam,407,Total Number of Invoice/Sales,RS_Session_254_AU_697_1.csv
18,West Bengal,771,Total Number of Invoice/Sales,RS_Session_254_AU_697_1.csv
19,Jharkhand,817,Total Number of Invoice/Sales,RS_Session_254_AU_697_1.csv
20,Odisha,1671,Total Number of Invoice/Sales,RS_Session_254_AU_697_1.csv
21,Chhattisgarh,2055,Total Number of Invoice/Sales,RS_Session_254_AU_697_1.csv
22,Madhya Pradesh,2953,Total Number of Invoice/Sales,RS_Session_254_AU_697_1.csv
23,Gujarat,1554,Total Number of Invoice/Sales,RS_Session_254_AU_697_1.csv
24,Maharashtra,9393,Total Number of Invoice/Sales,RS_Session_254_AU_697_1.csv
25,Andhra Pradesh,3325,Total Number of Invoice/Sales,RS_Session_254_AU_697_1.csv
26,Karnataka,19270,Total Number of Invoice/Sales,RS_Session_254_AU_697_1.csv
27,Goa,241,Total Number of Invoice/Sales,RS_Session_254_AU_697_1.csv
28,Lakshadweep,4,Total Number of Invoice/Sales,RS_Session_254_AU_697_1.csv
29,Kerala,2068,Total Number of Invoice/Sales,RS_Session_254_AU_697_1.csv
30,Tamilnadu,13515,Total Number of Invoice/Sales,RS_Session_254_AU_697_1.csv
31,Puducherry,138,Total Number of Invoice/Sales,RS_Session_254_AU_697_1.csv
32,Andaman and Nicobar Islands,2,Total Number of Invoice/Sales,RS_Session_254_AU_697_1.csv
33,Telangana,3031,Total Number of Invoice/Sales,RS_Session_254_AU_697_1.csv
34,Ladakh,0,Total Number of Invoice/Sales,RS_Session_254_AU_697_1.csv
35,The Dadra and Nagar Haveli and Daman and Diu,27,Total Number of Invoice/Sales,RS_Session_254_AU_697_1.csv
36,Jammu Kashmir,1036,Total Number of Invoices/Sales,RS_Session_255_AU_2349_2.csv
37,Himachal Pradesh,446,Total Number of Invoices/Sales,RS_Session_255_AU_2349_2.csv
38,Punjab,2977,Total Number of Invoices/Sales,RS_Session_255_AU_2349_2.csv
39,Chandigarh,154,Total Number of Invoices/Sales,RS_Session_255_AU_2349_2.csv
40,Uttarakhand,2288,Total Number of Invoices/Sales,RS_Session_255_AU_2349_2.csv
41,Haryana,4667,Total Number of Invoices/Sales,RS_Session_255_AU_2349_2.csv
42,Delhi,12850,Total Number of Invoices/Sales,RS_Session_255_AU_2349_2.csv
43,Rajasthan,14326,Total Number of Invoices/Sales,RS_Session_255_AU_2349_2.csv
44,Uttar Pradesh,11853,Total Number of Invoices/Sales,RS_Session_255_AU_2349_2.csv
45,Bihar,5255,Total Number of Invoices/Sales,RS_Session_255_AU_2349_2.csv
46,Sikkim,1,Total Number of Invoices/Sales,RS_Session_255_AU_2349_2.csv
47,Arunachal Pradesh,1,Total Number of Invoices/Sales,RS_Session_255_AU_2349_2.csv
48,Manipur,140,Total Number of Invoices/Sales,RS_Session_255_AU_2349_2.csv
49,Tripura,750,Total Number of Invoices/Sales,RS_Session_255_AU_2349_2.csv
50,Meghalaya,10,Total Number of Invoices/Sales,RS_Session_255_AU_2349_2.csv
51,Assam,827,Total Number of Invoices/Sales,RS_Session_255_AU_2349_2.csv
52,West Bengal,1347,Total Number of Invoices/Sales,RS_Session_255_AU_2349_2.csv
53,Jharkhand,1874,Total Number of Invoices/Sales,RS_Session_255_AU_2349_2.csv
54,Odisha,4454,Total Number of Invoices/Sales,RS_Session_255_AU_2349_2.csv
55,Chhattisgarh,3573,Total Number of Invoices/Sales,RS_Session_255_AU_2349_2.csv
56,Madhya Pradesh,6306,Total Number of Invoices/Sales,RS_Session_255_AU_2349_2.csv
57,Gujarat,5839,Total Number of Invoices/Sales,RS_Session_255_AU_2349_2.csv
58,Maharashtra,20955,Total Number of Invoices/Sales,RS_Session_255_AU_2349_2.csv
59,Andhra Pradesh,6393,Total Number of Invoices/Sales,RS_Session_255_AU_2349_2.csv
60,Karnataka,33483,Total Number of Invoices/Sales,RS_Session_255_AU_2349_2.csv
61,Goa,614,Total Number of Invoices/Sales,RS_Session_255_AU_2349_2.csv
62,Lakshadweep,4,Total Number of Invoices/Sales,RS_Session_255_AU_2349_2.csv
63,Kerala,4851,Total Number of Invoices/Sales,RS_Session_255_AU_2349_2.csv
64,Tamil Nadu,24632,Total Number of Invoices/Sales,RS_Session_255_AU_2349_2.csv
65,Puducherry,259,Total Number of Invoices/Sales,RS_Session_255_AU_2349_2.csv
66,Andaman and Nicobar Islands,3,Total Number of Invoices/Sales,RS_Session_255_AU_2349_2.csv
67,Telangana,6316,Total Number of Invoices/Sales,RS_Session_255_AU_2349_2.csv
68,Ladakh,6,Total Number of Invoices/Sales,RS_Session_255_AU_2349_2.csv
69,Dadra and Nagar Haveli and Daman and Diu,31,Total Number of Invoices/Sales,RS_Session_255_AU_2349_2.csv
70,Andaman and Nicobar Island,182,Electric Vehicle Count,RS_Session_259_AU_3475_1.csv
71,Andhra Pradesh,51322,Electric Vehicle Count,RS_Session_259_AU_3475_1.csv
72,Arunachal Pradesh,24,Electric Vehicle Count,RS_Session_259_AU_3475_1.csv
73,Assam,94929,Electric Vehicle Count,RS_Session_259_AU_3475_1.csv
74,Bihar,128885,Electric Vehicle Count,RS_Session_259_AU_3475_1.csv
75,Chandigarh,5533,Electric Vehicle Count,RS_Session_259_AU_3475_1.csv
76,Chhattisgarh,40516,Electric Vehicle Count,RS_Session_259_AU_3475_1.csv
77,Delhi,203263,Electric Vehicle Count,RS_Session_259_AU_3475_1.csv
78,Goa,8710,Electric Vehicle Count,RS_Session_259_AU_3475_1.csv
79,Gujarat,99236,Electric Vehicle Count,RS_Session_259_AU_3475_1.csv
80,Haryana,56243,Electric Vehicle Count,RS_Session_259_AU_3475_1.csv
81,Himachal Pradesh,1877,Electric Vehicle Count,RS_Session_259_AU_3475_1.csv
82,Jammu and Kashmir,7080,Electric Vehicle Count,RS_Session_259_AU_3475_1.csv
83,Jharkhand,28395,Electric Vehicle Count,RS_Session_259_AU_3475_1.csv
84,Karnataka,183536,Electric Vehicle Count,RS_Session_259_AU_3475_1.csv
85,Kerala,65545,Electric Vehicle Count,RS_Session_259_AU_3475_1.csv
86,Ladakh,47,Electric Vehicle Count,RS_Session_259_AU_3475_1.csv
87,Madhya Pradesh,42957,Electric Vehicle Count,RS_Session_259_AU_3475_1.csv
88,Maharashtra,226134,Electric Vehicle Count,RS_Session_259_AU_3475_1.csv
89,Manipur,1052,Electric Vehicle Count,RS_Session_259_AU_3475_1.csv
90,Meghalaya,83,Electric Vehicle Count,RS_Session_259_AU_3475_1.csv
91,Mizoram,76,Electric Vehicle Count,RS_Session_259_AU_3475_1.csv
92,Nagaland,60,Electric Vehicle Count,RS_Session_259_AU_3475_1.csv
93,Odisha,45562,Electric Vehicle Count,RS_Session_259_AU_3475_1.csv
94,Puducherry,3376,Electric Vehicle Count,RS_Session_259_AU_3475_1.csv
95,Punjab,25597,Electric Vehicle Count,RS_Session_259_AU_3475_1.csv
96,Rajasthan,143273,Electric Vehicle Count,RS_Session_259_AU_3475_1.csv
97,Sikkim,21,Electric Vehicle Count,RS_Session_259_AU_3475_1.csv
98,Tamil Nadu,129153,Electric Vehicle Count,RS_Session_259_AU_3475_1.csv
99,Tripura,12229,Electric Vehicle Count,RS_Session_259_AU_3475_1.csv
100,Dadra and Nagar Haveli and Daman and Diu,303,Electric Vehicle Count,RS_Session_259_AU_3475_1.csv
101,Uttar Pradesh,465432,Electric Vehicle Count,RS_Session_259_AU_3475_1.csv
102,Uttarakhand,42308,Electric Vehicle Count,RS_Session_259_AU_3475_1.csv
103,West Bengal,57512,Electric Vehicle Count,RS_Session_259_AU_3475_1.csv

In [20]:
df_cat = load_and_clean("RS_Session_256_AU_95_C.csv")
df_cat = df_cat[~df_cat["State Name"].astype(str).str.contains("Total", case=False, na=False)]

category_cols = [c for c in df_cat.columns if c not in ["State Name", "Grand Total"]]

master_state_vehicle_category = df_cat.melt(
    id_vars=["State Name"],
    value_vars=category_cols,
    var_name="vehicle_category",
    value_name="count"
).rename(columns={"State Name": "state"})
master_state_vehicle_category["source_file"] = "RS_Session_256_AU_95_C.csv"

master_state_vehicle_category.info()
master_state_vehicle_category

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 288 entries, 0 to 287
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   state             288 non-null    object
 1   vehicle_category  288 non-null    object
 2   count             191 non-null    float64
 3   source_file       288 non-null    object
dtypes: float64(1), object(3)
memory usage: 9.1+ KB

,state,vehicle_category,count,source_file
0,Andaman and Nicobar Island,Two Wheeler,1.0,RS_Session_256_AU_95_C.csv
1,Arunachal Pradesh,Two Wheeler,14.0,RS_Session_256_AU_95_C.csv
2,Assam,Two Wheeler,721.0,RS_Session_256_AU_95_C.csv
3,Bihar,Two Wheeler,5003.0,RS_Session_256_AU_95_C.csv
4,Chandigarh,Two Wheeler,298.0,RS_Session_256_AU_95_C.csv
5,Chhattisgarh,Two Wheeler,6424.0,RS_Session_256_AU_95_C.csv
6,Delhi,Two Wheeler,14730.0,RS_Session_256_AU_95_C.csv
7,Goa,Two Wheeler,1314.0,RS_Session_256_AU_95_C.csv
8,Gujarat,Two Wheeler,13662.0,RS_Session_256_AU_95_C.csv
9,Haryana,Two Wheeler,7777.0,RS_Session_256_AU_95_C.csv
10,Himachal Pradesh,Two Wheeler,368.0,RS_Session_256_AU_95_C.csv
11,Jammu and Kashmir,Two Wheeler,1417.0,RS_Session_256_AU_95_C.csv
12,Jharkhand,Two Wheeler,2961.0,RS_Session_256_AU_95_C.csv
13,Karnataka,Two Wheeler,56737.0,RS_Session_256_AU_95_C.csv
14,Kerala,Two Wheeler,10299.0,RS_Session_256_AU_95_C.csv
15,Ladakh,Two Wheeler,12.0,RS_Session_256_AU_95_C.csv
16,Maharashtra,Two Wheeler,51149.0,RS_Session_256_AU_95_C.csv
17,Manipur,Two Wheeler,86.0,RS_Session_256_AU_95_C.csv
18,Meghalaya,Two Wheeler,16.0,RS_Session_256_AU_95_C.csv
19,Mizoram,Two Wheeler,9.0,RS_Session_256_AU_95_C.csv
20,Nagaland,Two Wheeler,44.0,RS_Session_256_AU_95_C.csv
21,Odisha,Two Wheeler,10329.0,RS_Session_256_AU_95_C.csv
22,Puducherry,Two Wheeler,1429.0,RS_Session_256_AU_95_C.csv
23,Punjab,Two Wheeler,6408.0,RS_Session_256_AU_95_C.csv
24,Rajasthan,Two Wheeler,23446.0,RS_Session_256_AU_95_C.csv
25,Sikkim,Two Wheeler,1.0,RS_Session_256_AU_95_C.csv
26,Tamil Nadu,Two Wheeler,44302.0,RS_Session_256_AU_95_C.csv
27,Tripura,Two Wheeler,67.0,RS_Session_256_AU_95_C.csv
28,Dadra and Nagar Haveli and Daman and Diu,Two Wheeler,69.0,RS_Session_256_AU_95_C.csv
29,Uttar Pradesh,Two Wheeler,18295.0,RS_Session_256_AU_95_C.csv
30,Uttarakhand,Two Wheeler,2614.0,RS_Session_256_AU_95_C.csv
31,West Bengal,Two Wheeler,2540.0,RS_Session_256_AU_95_C.csv
32,Andaman and Nicobar Island,Three Wheeler,30.0,RS_Session_256_AU_95_C.csv
33,Arunachal Pradesh,Three Wheeler,NaN,RS_Session_256_AU_95_C.csv
34,Assam,Three Wheeler,47041.0,RS_Session_256_AU_95_C.csv
35,Bihar,Three Wheeler,59079.0,RS_Session_256_AU_95_C.csv
36,Chandigarh,Three Wheeler,1410.0,RS_Session_256_AU_95_C.csv
37,Chhattisgarh,Three Wheeler,5341.0,RS_Session_256_AU_95_C.csv
38,Delhi,Three Wheeler,112831.0,RS_Session_256_AU_95_C.csv
39,Goa,Three Wheeler,28.0,RS_Session_256_AU_95_C.csv
40,Gujarat,Three Wheeler,1869.0,RS_Session_256_AU_95_C.csv
41,Haryana,Three Wheeler,18595.0,RS_Session_256_AU_95_C.csv
42,Himachal Pradesh,Three Wheeler,167.0,RS_Session_256_AU_95_C.csv
43,Jammu and Kashmir,Three Wheeler,43.0,RS_Session_256_AU_95_C.csv
44,Jharkhand,Three Wheeler,8986.0,RS_Session_256_AU_95_C.csv
45,Karnataka,Three Wheeler,16478.0,RS_Session_256_AU_95_C.csv
46,Kerala,Three Wheeler,2115.0,RS_Session_256_AU_95_C.csv
47,Ladakh,Three Wheeler,NaN,RS_Session_256_AU_95_C.csv
48,Maharashtra,Three Wheeler,6155.0,RS_Session_256_AU_95_C.csv
49,Manipur,Three Wheeler,443.0,RS_Session_256_AU_95_C.csv
50,Meghalaya,Three Wheeler,6.0,RS_Session_256_AU_95_C.csv
51,Mizoram,Three Wheeler,1.0,RS_Session_256_AU_95_C.csv
52,Nagaland,Three Wheeler,NaN,RS_Session_256_AU_95_C.csv
53,Odisha,Three Wheeler,1808.0,RS_Session_256_AU_95_C.csv
54,Puducherry,Three Wheeler,32.0,RS_Session_256_AU_95_C.csv
55,Punjab,Three Wheeler,2878.0,RS_Session_256_AU_95_C.csv
56,Rajasthan,Three Wheeler,29631.0,RS_Session_256_AU_95_C.csv
57,Sikkim,Three Wheeler,NaN,RS_Session_256_AU_95_C.csv
58,Tamil Nadu,Three Wheeler,4470.0,RS_Session_256_AU_95_C.csv
59,Tripura,Three Wheeler,7510.0,RS_Session_256_AU_95_C.csv
60,Dadra and Nagar Haveli and Daman and Diu,Three Wheeler,36.0,RS_Session_256_AU_95_C.csv
61,Uttar Pradesh,Three Wheeler,257159.0,RS_Session_256_AU_95_C.csv
62,Uttarakhand,Three Wheeler,22096.0,RS_Session_256_AU_95_C.csv
63,West Bengal,Three Wheeler,40948.0,RS_Session_256_AU_95_C.csv
64,Andaman and Nicobar Island,Four Wheeler,81.0,RS_Session_256_AU_95_C.csv
65,Arunachal Pradesh,Four Wheeler,5.0,RS_Session_256_AU_95_C.csv
66,Assam,Four Wheeler,161.0,RS_Session_256_AU_95_C.csv
67,Bihar,Four Wheeler,114.0,RS_Session_256_AU_95_C.csv
68,Chandigarh,Four Wheeler,182.0,RS_Session_256_AU_95_C.csv
69,Chhattisgarh,Four Wheeler,117.0,RS_Session_256_AU_95_C.csv
70,Delhi,Four Wheeler,3051.0,RS_Session_256_AU_95_C.csv
71,Goa,Four Wheeler,289.0,RS_Session_256_AU_95_C.csv
72,Gujarat,Four Wheeler,1309.0,RS_Session_256_AU_95_C.csv
73,Haryana,Four Wheeler,186.0,RS_Session_256_AU_95_C.csv
74,Himachal Pradesh,Four Wheeler,37.0,RS_Session_256_AU_95_C.csv
75,Jammu and Kashmir,Four Wheeler,10.0,RS_Session_256_AU_95_C.csv
76,Jharkhand,Four Wheeler,139.0,RS_Session_256_AU_95_C.csv
77,Karnataka,Four Wheeler,7212.0,RS_Session_256_AU_95_C.csv
78,Kerala,Four Wheeler,2524.0,RS_Session_256_AU_95_C.csv
79,Ladakh,Four Wheeler,5484.0,RS_Session_256_AU_95_C.csv
80,Maharashtra,Four Wheeler,2.0,RS_Session_256_AU_95_C.csv
81,Manipur,Four Wheeler,9.0,RS_Session_256_AU_95_C.csv
82,Meghalaya,Four Wheeler,3.0,RS_Session_256_AU_95_C.csv
83,Mizoram,Four Wheeler,4.0,RS_Session_256_AU_95_C.csv
84,Nagaland,Four Wheeler,121.0,RS_Session_256_AU_95_C.csv
85,Odisha,Four Wheeler,75.0,RS_Session_256_AU_95_C.csv
86,Puducherry,Four Wheeler,124.0,RS_Session_256_AU_95_C.csv
87,Punjab,Four Wheeler,798.0,RS_Session_256_AU_95_C.csv
88,Rajasthan,Four Wheeler,12.0,RS_Session_256_AU_95_C.csv
89,Sikkim,Four Wheeler,2414.0,RS_Session_256_AU_95_C.csv
90,Tamil Nadu,Four Wheeler,13.0,RS_Session_256_AU_95_C.csv
91,Tripura,Four Wheeler,14.0,RS_Session_256_AU_95_C.csv
92,Dadra and Nagar Haveli and Daman and Diu,Four Wheeler,153.0,RS_Session_256_AU_95_C.csv
93,Uttar Pradesh,Four Wheeler,368.0,RS_Session_256_AU_95_C.csv
94,Uttarakhand,Four Wheeler,709.0,RS_Session_256_AU_95_C.csv
95,West Bengal,Four Wheeler,615.0,RS_Session_256_AU_95_C.csv
96,Andaman and Nicobar Island,Goods Vehicles,NaN,RS_Session_256_AU_95_C.csv
97,Arunachal Pradesh,Goods Vehicles,NaN,RS_Session_256_AU_95_C.csv
98,Assam,Goods Vehicles,7.0,RS_Session_256_AU_95_C.csv
99,Bihar,Goods Vehicles,11.0,RS_Session_256_AU_95_C.csv
100,Chandigarh,Goods Vehicles,NaN,RS_Session_256_AU_95_C.csv
101,Chhattisgarh,Goods Vehicles,1077.0,RS_Session_256_AU_95_C.csv
102,Delhi,Goods Vehicles,49.0,RS_Session_256_AU_95_C.csv
103,Goa,Goods Vehicles,13.0,RS_Session_256_AU_95_C.csv
104,Gujarat,Goods Vehicles,28.0,RS_Session_256_AU_95_C.csv
105,Haryana,Goods Vehicles,122.0,RS_Session_256_AU_95_C.csv
106,Himachal Pradesh,Goods Vehicles,7.0,RS_Session_256_AU_95_C.csv
107,Jammu and Kashmir,Goods Vehicles,6.0,RS_Session_256_AU_95_C.csv
108,Jharkhand,Goods Vehicles,24.0,RS_Session_256_AU_95_C.csv
109,Karnataka,Goods Vehicles,153.0,RS_Session_256_AU_95_C.csv
110,Kerala,Goods Vehicles,43.0,RS_Session_256_AU_95_C.csv
111,Ladakh,Goods Vehicles,NaN,RS_Session_256_AU_95_C.csv
112,Maharashtra,Goods Vehicles,30.0,RS_Session_256_AU_95_C.csv
113,Manipur,Goods Vehicles,1.0,RS_Session_256_AU_95_C.csv
114,Meghalaya,Goods Vehicles,3.0,RS_Session_256_AU_95_C.csv
115,Mizoram,Goods Vehicles,2.0,RS_Session_256_AU_95_C.csv
116,Nagaland,Goods Vehicles,3.0,RS_Session_256_AU_95_C.csv
117,Odisha,Goods Vehicles,21.0,RS_Session_256_AU_95_C.csv
118,Puducherry,Goods Vehicles,9.0,RS_Session_256_AU_95_C.csv
119,Punjab,Goods Vehicles,35.0,RS_Session_256_AU_95_C.csv
120,Rajasthan,Goods Vehicles,25.0,RS_Session_256_AU_95_C.csv
121,Sikkim,Goods Vehicles,1.0,RS_Session_256_AU_95_C.csv
122,Tamil Nadu,Goods Vehicles,1281.0,RS_Session_256_AU_95_C.csv
123,Tripura,Goods Vehicles,1.0,RS_Session_256_AU_95_C.csv
124,Dadra and Nagar Haveli and Daman and Diu,Goods Vehicles,2.0,RS_Session_256_AU_95_C.csv
125,Uttar Pradesh,Goods Vehicles,53.0,RS_Session_256_AU_95_C.csv
126,Uttarakhand,Goods Vehicles,1.0,RS_Session_256_AU_95_C.csv
127,West Bengal,Goods Vehicles,28.0,RS_Session_256_AU_95_C.csv
128,Andaman and Nicobar Island,Public Service Vehicle,40.0,RS_Session_256_AU_95_C.csv
129,Arunachal Pradesh,Public Service Vehicle,NaN,RS_Session_256_AU_95_C.csv
130,Assam,Public Service Vehicle,15.0,RS_Session_256_AU_95_C.csv
131,Bihar,Public Service Vehicle,26.0,RS_Session_256_AU_95_C.csv
132,Chandigarh,Public Service Vehicle,40.0,RS_Session_256_AU_95_C.csv
133,Chhattisgarh,Public Service Vehicle,1.0,RS_Session_256_AU_95_C.csv
134,Delhi,Public Service Vehicle,39.0,RS_Session_256_AU_95_C.csv
135,Goa,Public Service Vehicle,36.0,RS_Session_256_AU_95_C.csv
136,Gujarat,Public Service Vehicle,278.0,RS_Session_256_AU_95_C.csv
137,Haryana,Public Service Vehicle,8.0,RS_Session_256_AU_95_C.csv
138,Himachal Pradesh,Public Service Vehicle,86.0,RS_Session_256_AU_95_C.csv
139,Jammu and Kashmir,Public Service Vehicle,43.0,RS_Session_256_AU_95_C.csv
140,Jharkhand,Public Service Vehicle,4.0,RS_Session_256_AU_95_C.csv
141,Karnataka,Public Service Vehicle,44.0,RS_Session_256_AU_95_C.csv
142,Kerala,Public Service Vehicle,23.0,RS_Session_256_AU_95_C.csv
143,Ladakh,Public Service Vehicle,NaN,RS_Session_256_AU_95_C.csv
144,Maharashtra,Public Service Vehicle,851.0,RS_Session_256_AU_95_C.csv
145,Manipur,Public Service Vehicle,NaN,RS_Session_256_AU_95_C.csv
146,Meghalaya,Public Service Vehicle,NaN,RS_Session_256_AU_95_C.csv
147,Mizoram,Public Service Vehicle,1.0,RS_Session_256_AU_95_C.csv
148,Nagaland,Public Service Vehicle,NaN,RS_Session_256_AU_95_C.csv
149,Odisha,Public Service Vehicle,NaN,RS_Session_256_AU_95_C.csv
150,Puducherry,Public Service Vehicle,20.0,RS_Session_256_AU_95_C.csv
151,Punjab,Public Service Vehicle,2.0,RS_Session_256_AU_95_C.csv
152,Rajasthan,Public Service Vehicle,1.0,RS_Session_256_AU_95_C.csv
153,Sikkim,Public Service Vehicle,NaN,RS_Session_256_AU_95_C.csv
154,Tamil Nadu,Public Service Vehicle,37.0,RS_Session_256_AU_95_C.csv
155,Tripura,Public Service Vehicle,NaN,RS_Session_256_AU_95_C.csv
156,Dadra and Nagar Haveli and Daman and Diu,Public Service Vehicle,10.0,RS_Session_256_AU_95_C.csv
157,Uttar Pradesh,Public Service Vehicle,327.0,RS_Session_256_AU_95_C.csv
158,Uttarakhand,Public Service Vehicle,10.0,RS_Session_256_AU_95_C.csv
159,West Bengal,Public Service Vehicle,97.0,RS_Session_256_AU_95_C.csv
160,Andaman and Nicobar Island,Special Category Vehicles,NaN,RS_Session_256_AU_95_C.csv
161,Arunachal Pradesh,Special Category Vehicles,NaN,RS_Session_256_AU_95_C.csv
162,Assam,Special Category Vehicles,NaN,RS_Session_256_AU_95_C.csv
163,Bihar,Special Category Vehicles,NaN,RS_Session_256_AU_95_C.csv
164,Chandigarh,Special Category Vehicles,NaN,RS_Session_256_AU_95_C.csv
165,Chhattisgarh,Special Category Vehicles,NaN,RS_Session_256_AU_95_C.csv
166,Delhi,Special Category Vehicles,NaN,RS_Session_256_AU_95_C.csv
167,Goa,Special Category Vehicles,2.0,RS_Session_256_AU_95_C.csv
168,Gujarat,Special Category Vehicles,344.0,RS_Session_256_AU_95_C.csv
169,Haryana,Special Category Vehicles,2.0,RS_Session_256_AU_95_C.csv
170,Himachal Pradesh,Special Category Vehicles,NaN,RS_Session_256_AU_95_C.csv
171,Jammu and Kashmir,Special Category Vehicles,NaN,RS_Session_256_AU_95_C.csv
172,Jharkhand,Special Category Vehicles,NaN,RS_Session_256_AU_95_C.csv
173,Karnataka,Special Category Vehicles,1.0,RS_Session_256_AU_95_C.csv
174,Kerala,Special Category Vehicles,NaN,RS_Session_256_AU_95_C.csv
175,Ladakh,Special Category Vehicles,NaN,RS_Session_256_AU_95_C.csv
176,Maharashtra,Special Category Vehicles,26.0,RS_Session_256_AU_95_C.csv
177,Manipur,Special Category Vehicles,NaN,RS_Session_256_AU_95_C.csv
178,Meghalaya,Special Category Vehicles,NaN,RS_Session_256_AU_95_C.csv
179,Mizoram,Special Category Vehicles,NaN,RS_Session_256_AU_95_C.csv
180,Nagaland,Special Category Vehicles,1.0,RS_Session_256_AU_95_C.csv
181,Odisha,Special Category Vehicles,25.0,RS_Session_256_AU_95_C.csv
182,Puducherry,Special Category Vehicles,NaN,RS_Session_256_AU_95_C.csv
183,Punjab,Special Category Vehicles,NaN,RS_Session_256_AU_95_C.csv
184,Rajasthan,Special Category Vehicles,NaN,RS_Session_256_AU_95_C.csv
185,Sikkim,Special Category Vehicles,NaN,RS_Session_256_AU_95_C.csv
186,Tamil Nadu,Special Category Vehicles,NaN,RS_Session_256_AU_95_C.csv
187,Tripura,Special Category Vehicles,NaN,RS_Session_256_AU_95_C.csv
188,Dadra and Nagar Haveli and Daman and Diu,Special Category Vehicles,7.0,RS_Session_256_AU_95_C.csv
189,Uttar Pradesh,Special Category Vehicles,2.0,RS_Session_256_AU_95_C.csv
190,Uttarakhand,Special Category Vehicles,NaN,RS_Session_256_AU_95_C.csv
191,West Bengal,Special Category Vehicles,NaN,RS_Session_256_AU_95_C.csv
192,Andaman and Nicobar Island,Ambulance/Hearses,NaN,RS_Session_256_AU_95_C.csv
193,Arunachal Pradesh,Ambulance/Hearses,NaN,RS_Session_256_AU_95_C.csv
194,Assam,Ambulance/Hearses,NaN,RS_Session_256_AU_95_C.csv
195,Bihar,Ambulance/Hearses,NaN,RS_Session_256_AU_95_C.csv
196,Chandigarh,Ambulance/Hearses,NaN,RS_Session_256_AU_95_C.csv
197,Chhattisgarh,Ambulance/Hearses,NaN,RS_Session_256_AU_95_C.csv
198,Delhi,Ambulance/Hearses,NaN,RS_Session_256_AU_95_C.csv
199,Goa,Ambulance/Hearses,NaN,RS_Session_256_AU_95_C.csv
200,Gujarat,Ambulance/Hearses,NaN,RS_Session_256_AU_95_C.csv
201,Haryana,Ambulance/Hearses,NaN,RS_Session_256_AU_95_C.csv
202,Himachal Pradesh,Ambulance/Hearses,NaN,RS_Session_256_AU_95_C.csv
203,Jammu and Kashmir,Ambulance/Hearses,NaN,RS_Session_256_AU_95_C.csv
204,Jharkhand,Ambulance/Hearses,NaN,RS_Session_256_AU_95_C.csv
205,Karnataka,Ambulance/Hearses,1.0,RS_Session_256_AU_95_C.csv
206,Kerala,Ambulance/Hearses,1.0,RS_Session_256_AU_95_C.csv
207,Ladakh,Ambulance/Hearses,NaN,RS_Session_256_AU_95_C.csv
208,Maharashtra,Ambulance/Hearses,1.0,RS_Session_256_AU_95_C.csv
209,Manipur,Ambulance/Hearses,NaN,RS_Session_256_AU_95_C.csv
210,Meghalaya,Ambulance/Hearses,NaN,RS_Session_256_AU_95_C.csv
211,Mizoram,Ambulance/Hearses,NaN,RS_Session_256_AU_95_C.csv
212,Nagaland,Ambulance/Hearses,NaN,RS_Session_256_AU_95_C.csv
213,Odisha,Ambulance/Hearses,NaN,RS_Session_256_AU_95_C.csv
214,Puducherry,Ambulance/Hearses,NaN,RS_Session_256_AU_95_C.csv
215,Punjab,Ambulance/Hearses,NaN,RS_Session_256_AU_95_C.csv
216,Rajasthan,Ambulance/Hearses,1.0,RS_Session_256_AU_95_C.csv
217,Sikkim,Ambulance/Hearses,NaN,RS_Session_256_AU_95_C.csv
218,Tamil Nadu,Ambulance/Hearses,NaN,RS_Session_256_AU_95_C.csv
219,Tripura,Ambulance/Hearses,NaN,RS_Session_256_AU_95_C.csv
220,Dadra and Nagar Haveli and Daman and Diu,Ambulance/Hearses,NaN,RS_Session_256_AU_95_C.csv
221,Uttar Pradesh,Ambulance/Hearses,NaN,RS_Session_256_AU_95_C.csv
222,Uttarakhand,Ambulance/Hearses,NaN,RS_Session_256_AU_95_C.csv
223,West Bengal,Ambulance/Hearses,2.0,RS_Session_256_AU_95_C.csv
224,Andaman and Nicobar Island,Construction Equipment Vehicle,NaN,RS_Session_256_AU_95_C.csv
225,Arunachal Pradesh,Construction Equipment Vehicle,NaN,RS_Session_256_AU_95_C.csv
226,Assam,Construction Equipment Vehicle,NaN,RS_Session_256_AU_95_C.csv
227,Bihar,Construction Equipment Vehicle,NaN,RS_Session_256_AU_95_C.csv
228,Chandigarh,Construction Equipment Vehicle,NaN,RS_Session_256_AU_95_C.csv
229,Chhattisgarh,Construction Equipment Vehicle,368.0,RS_Session_256_AU_95_C.csv
230,Delhi,Construction Equipment Vehicle,NaN,RS_Session_256_AU_95_C.csv
231,Goa,Construction Equipment Vehicle,NaN,RS_Session_256_AU_95_C.csv
232,Gujarat,Construction Equipment Vehicle,26.0,RS_Session_256_AU_95_C.csv
233,Haryana,Construction Equipment Vehicle,NaN,RS_Session_256_AU_95_C.csv
234,Himachal Pradesh,Construction Equipment Vehicle,NaN,RS_Session_256_AU_95_C.csv
235,Jammu and Kashmir,Construction Equipment Vehicle,NaN,RS_Session_256_AU_95_C.csv
236,Jharkhand,Construction Equipment Vehicle,NaN,RS_Session_256_AU_95_C.csv
237,Karnataka,Construction Equipment Vehicle,NaN,RS_Session_256_AU_95_C.csv
238,Kerala,Construction Equipment Vehicle,NaN,RS_Session_256_AU_95_C.csv
239,Ladakh,Construction Equipment Vehicle,NaN,RS_Session_256_AU_95_C.csv
240,Maharashtra,Construction Equipment Vehicle,NaN,RS_Session_256_AU_95_C.csv
241,Manipur,Construction Equipment Vehicle,NaN,RS_Session_256_AU_95_C.csv
242,Meghalaya,Construction Equipment Vehicle,NaN,RS_Session_256_AU_95_C.csv
243,Mizoram,Construction Equipment Vehicle,NaN,RS_Session_256_AU_95_C.csv
244,Nagaland,Construction Equipment Vehicle,1.0,RS_Session_256_AU_95_C.csv
245,Odisha,Construction Equipment Vehicle,1.0,RS_Session_256_AU_95_C.csv
246,Puducherry,Construction Equipment Vehicle,NaN,RS_Session_256_AU_95_C.csv
247,Punjab,Construction Equipment Vehicle,NaN,RS_Session_256_AU_95_C.csv
248,Rajasthan,Construction Equipment Vehicle,1.0,RS_Session_256_AU_95_C.csv
249,Sikkim,Construction Equipment Vehicle,NaN,RS_Session_256_AU_95_C.csv
250,Tamil Nadu,Construction Equipment Vehicle,NaN,RS_Session_256_AU_95_C.csv
251,Tripura,Construction Equipment Vehicle,NaN,RS_Session_256_AU_95_C.csv
252,Dadra and Nagar Haveli and Daman and Diu,Construction Equipment Vehicle,NaN,RS_Session_256_AU_95_C.csv
253,Uttar Pradesh,Construction Equipment Vehicle,NaN,RS_Session_256_AU_95_C.csv
254,Uttarakhand,Construction Equipment Vehicle,NaN,RS_Session_256_AU_95_C.csv
255,West Bengal,Construction Equipment Vehicle,NaN,RS_Session_256_AU_95_C.csv
256,Andaman and Nicobar Island,Other,7.0,RS_Session_256_AU_95_C.csv
257,Arunachal Pradesh,Other,1.0,RS_Session_256_AU_95_C.csv
258,Assam,Other,2.0,RS_Session_256_AU_95_C.csv
259,Bihar,Other,8.0,RS_Session_256_AU_95_C.csv
260,Chandigarh,Other,1.0,RS_Session_256_AU_95_C.csv
261,Chhattisgarh,Other,100.0,RS_Session_256_AU_95_C.csv
262,Delhi,Other,1602.0,RS_Session_256_AU_95_C.csv
263,Goa,Other,4.0,RS_Session_256_AU_95_C.csv
264,Gujarat,Other,77.0,RS_Session_256_AU_95_C.csv
265,Haryana,Other,90.0,RS_Session_256_AU_95_C.csv
266,Himachal Pradesh,Other,46.0,RS_Session_256_AU_95_C.csv
267,Jammu and Kashmir,Other,8.0,RS_Session_256_AU_95_C.csv
268,Jharkhand,Other,57.0,RS_Session_256_AU_95_C.csv
269,Karnataka,Other,1420.0,RS_Session_256_AU_95_C.csv
270,Kerala,Other,17.0,RS_Session_256_AU_95_C.csv
271,Ladakh,Other,NaN,RS_Session_256_AU_95_C.csv
272,Maharashtra,Other,601.0,RS_Session_256_AU_95_C.csv
273,Manipur,Other,1.0,RS_Session_256_AU_95_C.csv
274,Meghalaya,Other,NaN,RS_Session_256_AU_95_C.csv
275,Mizoram,Other,3.0,RS_Session_256_AU_95_C.csv
276,Nagaland,Other,1.0,RS_Session_256_AU_95_C.csv
277,Odisha,Other,23.0,RS_Session_256_AU_95_C.csv
278,Puducherry,Other,NaN,RS_Session_256_AU_95_C.csv
279,Punjab,Other,21.0,RS_Session_256_AU_95_C.csv
280,Rajasthan,Other,24.0,RS_Session_256_AU_95_C.csv
281,Sikkim,Other,9.0,RS_Session_256_AU_95_C.csv
282,Tamil Nadu,Other,193.0,RS_Session_256_AU_95_C.csv
283,Tripura,Other,1.0,RS_Session_256_AU_95_C.csv
284,Dadra and Nagar Haveli and Daman and Diu,Other,NaN,RS_Session_256_AU_95_C.csv
285,Uttar Pradesh,Other,13.0,RS_Session_256_AU_95_C.csv
286,Uttarakhand,Other,21.0,RS_Session_256_AU_95_C.csv
287,West Bengal,Other,61.0,RS_Session_256_AU_95_C.csv

In [19]:
df_ev_split = load_and_clean("RS_Session_260_AU_2349_A_to_B.csv")
df_ev_split = df_ev_split[~df_ev_split["State/UT"].astype(str).str.contains("Total", case=False, na=False)]

master_state_electric_split = df_ev_split.melt(
    id_vars=["State/UT"],
    value_vars=["Electric", "Non-electric"],
    var_name="category",
    value_name="count"
).rename(columns={"State/UT": "state"})
master_state_electric_split["source_file"] = "RS_Session_260_AU_2349_A_to_B.csv"

master_state_electric_split.info()
master_state_electric_split

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68 entries, 0 to 67
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   state        68 non-null     object
 1   category     68 non-null     object
 2   count        68 non-null     int64
 3   source_file  68 non-null     object
dtypes: int64(1), object(3)
memory usage: 2.3+ KB

,state,category,count,source_file
0,Andaman and Nicobar Islands,Electric,190,RS_Session_260_AU_2349_A_to_B.csv
1,Andhra Pradesh,Electric,67905,RS_Session_260_AU_2349_A_to_B.csv
2,Arunachal Pradesh,Electric,28,RS_Session_260_AU_2349_A_to_B.csv
3,Assam,Electric,120423,RS_Session_260_AU_2349_A_to_B.csv
4,Bihar,Electric,161060,RS_Session_260_AU_2349_A_to_B.csv
5,Chandigarh,Electric,7964,RS_Session_260_AU_2349_A_to_B.csv
6,Chhattisgarh,Electric,54848,RS_Session_260_AU_2349_A_to_B.csv
7,Delhi,Electric,233212,RS_Session_260_AU_2349_A_to_B.csv
8,Goa,Electric,12615,RS_Session_260_AU_2349_A_to_B.csv
9,Gujarat,Electric,138410,RS_Session_260_AU_2349_A_to_B.csv
10,Haryana,Electric,69271,RS_Session_260_AU_2349_A_to_B.csv
11,Himachal Pradesh,Electric,2410,RS_Session_260_AU_2349_A_to_B.csv
12,Jammu and Kashmir,Electric,10896,RS_Session_260_AU_2349_A_to_B.csv
13,Jharkhand,Electric,36759,RS_Session_260_AU_2349_A_to_B.csv
14,Karnataka,Electric,248747,RS_Session_260_AU_2349_A_to_B.csv
15,Kerala,Electric,98332,RS_Session_260_AU_2349_A_to_B.csv
16,Ladakh,Electric,65,RS_Session_260_AU_2349_A_to_B.csv
17,Madhya Pradesh,Electric,96151,RS_Session_260_AU_2349_A_to_B.csv
18,Maharashtra,Electric,305006,RS_Session_260_AU_2349_A_to_B.csv
19,Manipur,Electric,1203,RS_Session_260_AU_2349_A_to_B.csv
20,Meghalaya,Electric,139,RS_Session_260_AU_2349_A_to_B.csv
21,Mizoram,Electric,118,RS_Session_260_AU_2349_A_to_B.csv
22,Nagaland,Electric,62,RS_Session_260_AU_2349_A_to_B.csv
23,Odisha,Electric,62567,RS_Session_260_AU_2349_A_to_B.csv
24,Puducherry,Electric,4588,RS_Session_260_AU_2349_A_to_B.csv
25,Punjab,Electric,35727,RS_Session_260_AU_2349_A_to_B.csv
26,Rajasthan,Electric,180670,RS_Session_260_AU_2349_A_to_B.csv
27,Sikkim,Electric,20,RS_Session_260_AU_2349_A_to_B.csv
28,Tamil Nadu,Electric,173152,RS_Session_260_AU_2349_A_to_B.csv
29,Tripura,Electric,14839,RS_Session_260_AU_2349_A_to_B.csv
30,Dadra and Nagar Haveli and Daman and Diu,Electric,354,RS_Session_260_AU_2349_A_to_B.csv
31,Uttar Pradesh,Electric,574967,RS_Session_260_AU_2349_A_to_B.csv
32,Uttarakhand,Electric,49491,RS_Session_260_AU_2349_A_to_B.csv
33,West Bengal,Electric,68376,RS_Session_260_AU_2349_A_to_B.csv
34,Andaman and Nicobar Islands,Non-electric,161258,RS_Session_260_AU_2349_A_to_B.csv
35,Andhra Pradesh,Non-electric,16553509,RS_Session_260_AU_2349_A_to_B.csv
36,Arunachal Pradesh,Non-electric,303673,RS_Session_260_AU_2349_A_to_B.csv
37,Assam,Non-electric,5312457,RS_Session_260_AU_2349_A_to_B.csv
38,Bihar,Non-electric,11631081,RS_Session_260_AU_2349_A_to_B.csv
39,Chandigarh,Non-electric,841172,RS_Session_260_AU_2349_A_to_B.csv
40,Chhattisgarh,Non-electric,7413951,RS_Session_260_AU_2349_A_to_B.csv
41,Delhi,Non-electric,13994966,RS_Session_260_AU_2349_A_to_B.csv
42,Goa,Non-electric,1206476,RS_Session_260_AU_2349_A_to_B.csv
43,Gujarat,Non-electric,22804558,RS_Session_260_AU_2349_A_to_B.csv
44,Haryana,Non-electric,12062205,RS_Session_260_AU_2349_A_to_B.csv
45,Himachal Pradesh,Non-electric,2178827,RS_Session_260_AU_2349_A_to_B.csv
46,Jammu and Kashmir,Non-electric,2055765,RS_Session_260_AU_2349_A_to_B.csv
47,Jharkhand,Non-electric,7057289,RS_Session_260_AU_2349_A_to_B.csv
48,Karnataka,Non-electric,29785247,RS_Session_260_AU_2349_A_to_B.csv
49,Kerala,Non-electric,16781110,RS_Session_260_AU_2349_A_to_B.csv
50,Ladakh,Non-electric,44430,RS_Session_260_AU_2349_A_to_B.csv
51,Madhya Pradesh,Non-electric,19616269,RS_Session_260_AU_2349_A_to_B.csv
52,Maharashtra,Non-electric,34323748,RS_Session_260_AU_2349_A_to_B.csv
53,Manipur,Non-electric,554994,RS_Session_260_AU_2349_A_to_B.csv
54,Meghalaya,Non-electric,519714,RS_Session_260_AU_2349_A_to_B.csv
55,Mizoram,Non-electric,355369,RS_Session_260_AU_2349_A_to_B.csv
56,Nagaland,Non-electric,418529,RS_Session_260_AU_2349_A_to_B.csv
57,Odisha,Non-electric,10638175,RS_Session_260_AU_2349_A_to_B.csv
58,Puducherry,Non-electric,1330320,RS_Session_260_AU_2349_A_to_B.csv
59,Punjab,Non-electric,13196875,RS_Session_260_AU_2349_A_to_B.csv
60,Rajasthan,Non-electric,18857703,RS_Session_260_AU_2349_A_to_B.csv
61,Sikkim,Non-electric,109988,RS_Session_260_AU_2349_A_to_B.csv
62,Tamil Nadu,Non-electric,31618002,RS_Session_260_AU_2349_A_to_B.csv
63,Tripura,Non-electric,707543,RS_Session_260_AU_2349_A_to_B.csv
64,Dadra and Nagar Haveli and Daman and Diu,Non-electric,374489,RS_Session_260_AU_2349_A_to_B.csv
65,Uttar Pradesh,Non-electric,43852548,RS_Session_260_AU_2349_A_to_B.csv
66,Uttarakhand,Non-electric,3647377,RS_Session_260_AU_2349_A_to_B.csv
67,West Bengal,Non-electric,15227219,RS_Session_260_AU_2349_A_to_B.csv

## Insights: State-wise EV Data

- EV adoption is highly concentrated geographically, not evenly spread —
  large states like Uttar Pradesh show EV counts in the hundreds of
  thousands, while smaller states/UTs (Andaman & Nicobar, Arunachal
  Pradesh) have counts in the dozens or low hundreds — several orders of
  magnitude apart.
- Even in "leading" states, EVs remain a tiny share of the total vehicle
  fleet — e.g. one state's electric vs. non-electric split showed under
  0.5% electrification when measured against total registered vehicles,
  not just against other EVs.
- Data-quality finding: two files with different filenames/session numbers
  (RS_Session_258_AU_429_1.csv and RS_Session_258_AU_91_1.csv) turned out
  to contain identical state-level totals — a reminder that government
  open-data releases can duplicate/overlap, and blind merging without a
  verification step would have silently doubled every state's numbers.
- Several category/type-code breakdowns have missing values (NaN) for some
  states — likely representing zero vehicles in that category rather than
  missing data, since the original wide tables just left those cells
  blank. To be confirmed and converted during analysis, not assumed here.

In [23]:
for f in theme_groups["charging_infrastructure"]:
    df = load_and_clean(f)
    print(f"\n{f} — shape {df.shape}")
    display(df.head(2))

RS_Session_256_AU_2673_1.csv — shape (16, 3)

  Category City/Highway  Charging Stations
0     City   Chandigarh                 48
1     City        Delhi                 94

RS_Session_256_AU_2673_2.ii_.csv — shape (26, 4)

  Sl. No     Category  Expressways/Highways  EV Charging Stations Sanctioned
0      1  Expressways         Mumbai - Pune                               10
1      2  Expressways  Ahmadabad - Vadodara                               10

RS_Session_257_AS_71_A.ii_.csv — shape (14, 3)

  Sl. No.   State/UT  Operational Charging Stations Under FAME-I
0       1  Telangana                                          57
1       2  Jharkhand                                          30

RS_Session_259_AU_2474_A.csv — shape (3, 4)

,Charging Stations details,Organization,Sanctioned,Installed
0,"Solar Based Charging Infrastructure for EVs in NCR by REIL, Jaipur","REIL, Jaipur",3,3
1,Solar Grid Hybrid and Grid powered Charging Station along Delhi-Jaipur-Agra Highway,REIL,25,25

RS_Session_259_AU_2837_A.csv — shape (35, 3)

  Sl. No.             State/UT  No. of Operational PCS
0       1  Andaman and Nicobar                       3
1       2       Andhra Pradesh                     222

RS_Session_259_AU_2837_B.csv — shape (91, 2)

      National Highway  No. of Operational PCS
0  National Highway-10                       1
1  National Highway-11                       3

RS_Session_265_AU_2151_E.csv — shape (35, 3)

  Sl. No.                    State/ UT  No. of PCS as on 31st March 2024
0       1  Andaman and Nicobar Islands                                 3
1       2               Andhra Pradesh                               327

RS_Session_266_AU_2960_B_i.csv — shape (37, 3)

  Sl. No.     State/UT  No. of EVPCS
0       1    Karnataka          5765
1       2  Maharashtra          3728

RS_Session_266_AU_2960_C_to_D_i.csv — shape (32, 3)

  Sl. No.  District  No. of EVPCS
0       1    Raipur            57
1       2  Bilaspur            28

RS_Session_267_AU_581_C_i.csv — shape (37, 5)

,Sl. No.,State/UT,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charger installed as on 01-01-2025,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charging Stations energized as on 01-01-2025,Total No. of EV charging stations installed by OMCs from their own funds as on 01-01-2025
0,1,Andaman and Nicobar Islands,0,0,6
1,2,Andhra Pradesh,354,20,912

In [24]:
group_a_files = {
    "RS_Session_257_AS_71_A.ii_.csv": "Operational Charging Stations Under FAME-I",
    "RS_Session_259_AU_2837_A.csv": "No. of Operational PCS",
    "RS_Session_265_AU_2151_E.csv": "No. of PCS as on 31st March 2024",
    "RS_Session_266_AU_2960_B_i.csv": "No. of EVPCS",
}

frames = []
for f, value_col in group_a_files.items():
    df = load_and_clean(f)
    state_col = "State/UT" if "State/UT" in df.columns else "State/ UT"
    df = df.rename(columns={state_col: "state", value_col: "count"})
    df["metric"] = value_col
    df["source_file"] = f
    frames.append(df[["state", "count", "metric", "source_file"]])

master_charging_state_simple = pd.concat(frames, ignore_index=True)
master_charging_state_simple = master_charging_state_simple[
    ~master_charging_state_simple["state"].astype(str).str.contains("Total", case=False, na=False)
].reset_index(drop=True)

master_charging_state_simple.info()
master_charging_state_simple

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117 entries, 0 to 116
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   state        117 non-null    object
 1   count        117 non-null    int64
 2   metric       117 non-null    object
 3   source_file  117 non-null    object
dtypes: int64(1), object(3)
memory usage: 3.8+ KB

,state,count,metric,source_file
0,Telangana,57,Operational Charging Stations Under FAME-I,RS_Session_257_AS_71_A.ii_.csv
1,Jharkhand,30,Operational Charging Stations Under FAME-I,RS_Session_257_AS_71_A.ii_.csv
2,Goa,30,Operational Charging Stations Under FAME-I,RS_Session_257_AS_71_A.ii_.csv
3,Karnataka,65,Operational Charging Stations Under FAME-I,RS_Session_257_AS_71_A.ii_.csv
4,Himachal Pradesh,9,Operational Charging Stations Under FAME-I,RS_Session_257_AS_71_A.ii_.csv
5,Uttar Pradesh,16,Operational Charging Stations Under FAME-I,RS_Session_257_AS_71_A.ii_.csv
6,Rajasthan,49,Operational Charging Stations Under FAME-I,RS_Session_257_AS_71_A.ii_.csv
7,Delhi,94,Operational Charging Stations Under FAME-I,RS_Session_257_AS_71_A.ii_.csv
8,Chandigarh UT,48,Operational Charging Stations Under FAME-I,RS_Session_257_AS_71_A.ii_.csv
9,Delhi-Jaipur- Agra Highway,31,Operational Charging Stations Under FAME-I,RS_Session_257_AS_71_A.ii_.csv
10,Mumbai-Pune Expressway,17,Operational Charging Stations Under FAME-I,RS_Session_257_AS_71_A.ii_.csv
11,Jaipur- Delhi Highway,9,Operational Charging Stations Under FAME-I,RS_Session_257_AS_71_A.ii_.csv
12,Delhi- Chandigarh Highway,24,Operational Charging Stations Under FAME-I,RS_Session_257_AS_71_A.ii_.csv
13,Andaman and Nicobar,3,No. of Operational PCS,RS_Session_259_AU_2837_A.csv
14,Andhra Pradesh,222,No. of Operational PCS,RS_Session_259_AU_2837_A.csv
15,Arunachal Pradesh,9,No. of Operational PCS,RS_Session_259_AU_2837_A.csv
16,Assam,48,No. of Operational PCS,RS_Session_259_AU_2837_A.csv
17,Bihar,83,No. of Operational PCS,RS_Session_259_AU_2837_A.csv
18,Chandigarh,6,No. of Operational PCS,RS_Session_259_AU_2837_A.csv
19,Chhattisgarh,46,No. of Operational PCS,RS_Session_259_AU_2837_A.csv
20,Delhi,1845,No. of Operational PCS,RS_Session_259_AU_2837_A.csv
21,Goa,44,No. of Operational PCS,RS_Session_259_AU_2837_A.csv
22,Gujarat,195,No. of Operational PCS,RS_Session_259_AU_2837_A.csv
23,Haryana,232,No. of Operational PCS,RS_Session_259_AU_2837_A.csv
24,Himachal Pradesh,27,No. of Operational PCS,RS_Session_259_AU_2837_A.csv
25,Jammu and Kashmir,24,No. of Operational PCS,RS_Session_259_AU_2837_A.csv
26,Jharkhand,60,No. of Operational PCS,RS_Session_259_AU_2837_A.csv
27,Karnataka,704,No. of Operational PCS,RS_Session_259_AU_2837_A.csv
28,Kerala,192,No. of Operational PCS,RS_Session_259_AU_2837_A.csv
29,Lakshadweep,1,No. of Operational PCS,RS_Session_259_AU_2837_A.csv
30,Madhya Pradesh,174,No. of Operational PCS,RS_Session_259_AU_2837_A.csv
31,Maharashtra,660,No. of Operational PCS,RS_Session_259_AU_2837_A.csv
32,Manipur,16,No. of Operational PCS,RS_Session_259_AU_2837_A.csv
33,Meghalaya,19,No. of Operational PCS,RS_Session_259_AU_2837_A.csv
34,Nagaland,6,No. of Operational PCS,RS_Session_259_AU_2837_A.csv
35,Odisha,117,No. of Operational PCS,RS_Session_259_AU_2837_A.csv
36,Puducherry,4,No. of Operational PCS,RS_Session_259_AU_2837_A.csv
37,Punjab,126,No. of Operational PCS,RS_Session_259_AU_2837_A.csv
38,Rajasthan,254,No. of Operational PCS,RS_Session_259_AU_2837_A.csv
39,Sikkim,1,No. of Operational PCS,RS_Session_259_AU_2837_A.csv
40,Tamil Nadu,441,No. of Operational PCS,RS_Session_259_AU_2837_A.csv
41,Telangana,365,No. of Operational PCS,RS_Session_259_AU_2837_A.csv
42,Tripura,18,No. of Operational PCS,RS_Session_259_AU_2837_A.csv
43,Dadra and Nagar Haveli and Daman and Diu,1,No. of Operational PCS,RS_Session_259_AU_2837_A.csv
44,Uttar Pradesh,406,No. of Operational PCS,RS_Session_259_AU_2837_A.csv
45,Uttarakhand,48,No. of Operational PCS,RS_Session_259_AU_2837_A.csv
46,West Bengal,189,No. of Operational PCS,RS_Session_259_AU_2837_A.csv
47,Andaman and Nicobar Islands,3,No. of PCS as on 31st March 2024,RS_Session_265_AU_2151_E.csv
48,Andhra Pradesh,327,No. of PCS as on 31st March 2024,RS_Session_265_AU_2151_E.csv
49,Arunachal Pradesh,9,No. of PCS as on 31st March 2024,RS_Session_265_AU_2151_E.csv
50,Assam,86,No. of PCS as on 31st March 2024,RS_Session_265_AU_2151_E.csv
51,Bihar,124,No. of PCS as on 31st March 2024,RS_Session_265_AU_2151_E.csv
52,Chandigarh,12,No. of PCS as on 31st March 2024,RS_Session_265_AU_2151_E.csv
53,Chhattisgarh,149,No. of PCS as on 31st March 2024,RS_Session_265_AU_2151_E.csv
54,Delhi,1886,No. of PCS as on 31st March 2024,RS_Session_265_AU_2151_E.csv
55,Goa,113,No. of PCS as on 31st March 2024,RS_Session_265_AU_2151_E.csv
56,Gujarat,476,No. of PCS as on 31st March 2024,RS_Session_265_AU_2151_E.csv
57,Haryana,377,No. of PCS as on 31st March 2024,RS_Session_265_AU_2151_E.csv
58,Himachal Pradesh,44,No. of PCS as on 31st March 2024,RS_Session_265_AU_2151_E.csv
59,Jammu and Kashmir,47,No. of PCS as on 31st March 2024,RS_Session_265_AU_2151_E.csv
60,Jharkhand,135,No. of PCS as on 31st March 2024,RS_Session_265_AU_2151_E.csv
61,Karnataka,5130,No. of PCS as on 31st March 2024,RS_Session_265_AU_2151_E.csv
62,Kerala,958,No. of PCS as on 31st March 2024,RS_Session_265_AU_2151_E.csv
63,Lakshadweep,1,No. of PCS as on 31st March 2024,RS_Session_265_AU_2151_E.csv
64,Madhya Pradesh,341,No. of PCS as on 31st March 2024,RS_Session_265_AU_2151_E.csv
65,Maharashtra,3083,No. of PCS as on 31st March 2024,RS_Session_265_AU_2151_E.csv
66,Manipur,17,No. of PCS as on 31st March 2024,RS_Session_265_AU_2151_E.csv
67,Meghalaya,21,No. of PCS as on 31st March 2024,RS_Session_265_AU_2151_E.csv
68,Nagaland,6,No. of PCS as on 31st March 2024,RS_Session_265_AU_2151_E.csv
69,Odisha,198,No. of PCS as on 31st March 2024,RS_Session_265_AU_2151_E.csv
70,Puducherry,23,No. of PCS as on 31st March 2024,RS_Session_265_AU_2151_E.csv
71,Punjab,158,No. of PCS as on 31st March 2024,RS_Session_265_AU_2151_E.csv
72,Rajasthan,500,No. of PCS as on 31st March 2024,RS_Session_265_AU_2151_E.csv
73,Sikkim,2,No. of PCS as on 31st March 2024,RS_Session_265_AU_2151_E.csv
74,Tamil Nadu,643,No. of PCS as on 31st March 2024,RS_Session_265_AU_2151_E.csv
75,Telangana,483,No. of PCS as on 31st March 2024,RS_Session_265_AU_2151_E.csv
76,Tripura,18,No. of PCS as on 31st March 2024,RS_Session_265_AU_2151_E.csv
77,Dadra and Nagar Haveli and Daman and Diu,1,No. of PCS as on 31st March 2024,RS_Session_265_AU_2151_E.csv
78,Uttar Pradesh,583,No. of PCS as on 31st March 2024,RS_Session_265_AU_2151_E.csv
79,Uttarakhand,76,No. of PCS as on 31st March 2024,RS_Session_265_AU_2151_E.csv
80,West Bengal,318,No. of PCS as on 31st March 2024,RS_Session_265_AU_2151_E.csv
81,Karnataka,5765,No. of EVPCS,RS_Session_266_AU_2960_B_i.csv
82,Maharashtra,3728,No. of EVPCS,RS_Session_266_AU_2960_B_i.csv
83,Uttar Pradesh,1989,No. of EVPCS,RS_Session_266_AU_2960_B_i.csv
84,Delhi,1941,No. of EVPCS,RS_Session_266_AU_2960_B_i.csv
85,Tamil Nadu,1413,No. of EVPCS,RS_Session_266_AU_2960_B_i.csv
86,Kerala,1212,No. of EVPCS,RS_Session_266_AU_2960_B_i.csv
87,Rajasthan,1129,No. of EVPCS,RS_Session_266_AU_2960_B_i.csv
88,Gujarat,992,No. of EVPCS,RS_Session_266_AU_2960_B_i.csv
89,Telangana,956,No. of EVPCS,RS_Session_266_AU_2960_B_i.csv
90,Madhya Pradesh,903,No. of EVPCS,RS_Session_266_AU_2960_B_i.csv
91,West Bengal,763,No. of EVPCS,RS_Session_266_AU_2960_B_i.csv
92,Haryana,709,No. of EVPCS,RS_Session_266_AU_2960_B_i.csv
93,Andhra Pradesh,601,No. of EVPCS,RS_Session_266_AU_2960_B_i.csv
94,Punjab,593,No. of EVPCS,RS_Session_266_AU_2960_B_i.csv
95,Odisha,488,No. of EVPCS,RS_Session_266_AU_2960_B_i.csv
96,Bihar,347,No. of EVPCS,RS_Session_266_AU_2960_B_i.csv
97,Assam,276,No. of EVPCS,RS_Session_266_AU_2960_B_i.csv
98,Chhattisgarh,271,No. of EVPCS,RS_Session_266_AU_2960_B_i.csv
99,Jharkhand,256,No. of EVPCS,RS_Session_266_AU_2960_B_i.csv
100,Uttarakhand,177,No. of EVPCS,RS_Session_266_AU_2960_B_i.csv
101,Jammu and Kashmir,159,No. of EVPCS,RS_Session_266_AU_2960_B_i.csv
102,Goa,137,No. of EVPCS,RS_Session_266_AU_2960_B_i.csv
103,Himachal Pradesh,106,No. of EVPCS,RS_Session_266_AU_2960_B_i.csv
104,Tripura,50,No. of EVPCS,RS_Session_266_AU_2960_B_i.csv
105,Manipur,46,No. of EVPCS,RS_Session_266_AU_2960_B_i.csv
106,Meghalaya,43,No. of EVPCS,RS_Session_266_AU_2960_B_i.csv
107,Puducherry,41,No. of EVPCS,RS_Session_266_AU_2960_B_i.csv
108,Arunachal Pradesh,41,No. of EVPCS,RS_Session_266_AU_2960_B_i.csv
109,Nagaland,28,No. of EVPCS,RS_Session_266_AU_2960_B_i.csv
110,Chandigarh,13,No. of EVPCS,RS_Session_266_AU_2960_B_i.csv
111,Mizoram,12,No. of EVPCS,RS_Session_266_AU_2960_B_i.csv
112,Dadra and Nagar Haveli and Daman and Diu,6,No. of EVPCS,RS_Session_266_AU_2960_B_i.csv
113,Sikkim,5,No. of EVPCS,RS_Session_266_AU_2960_B_i.csv
114,Andaman and Nicobar Islands,4,No. of EVPCS,RS_Session_266_AU_2960_B_i.csv
115,Lakshadweep,1,No. of EVPCS,RS_Session_266_AU_2960_B_i.csv
116,Ladakh,1,No. of EVPCS,RS_Session_266_AU_2960_B_i.csv

In [25]:
df_fame2 = load_and_clean("RS_Session_267_AU_581_C_i.csv")
df_fame2 = df_fame2[~df_fame2["State/UT"].astype(str).str.contains("Total", case=False, na=False)]

value_cols = [c for c in df_fame2.columns if c not in ["Sl. No.", "State/UT"]]

master_charging_fame2_detail = df_fame2.melt(
    id_vars=["State/UT"],
    value_vars=value_cols,
    var_name="metric",
    value_name="count"
).rename(columns={"State/UT": "state"})
master_charging_fame2_detail["source_file"] = "RS_Session_267_AU_581_C_i.csv"

master_charging_fame2_detail.info()
master_charging_fame2_detail

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   state        108 non-null    object
 1   metric       108 non-null    object
 2   count        108 non-null    int64
 3   source_file  108 non-null    object
dtypes: int64(1), object(3)
memory usage: 3.5+ KB

,state,metric,count,source_file
0,Andaman and Nicobar Islands,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charger installed as on 01-01-2025,0,RS_Session_267_AU_581_C_i.csv
1,Andhra Pradesh,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charger installed as on 01-01-2025,354,RS_Session_267_AU_581_C_i.csv
2,Arunachal Pradesh,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charger installed as on 01-01-2025,2,RS_Session_267_AU_581_C_i.csv
3,Assam,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charger installed as on 01-01-2025,83,RS_Session_267_AU_581_C_i.csv
4,Bihar,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charger installed as on 01-01-2025,58,RS_Session_267_AU_581_C_i.csv
5,Chandigarh,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charger installed as on 01-01-2025,0,RS_Session_267_AU_581_C_i.csv
6,Chhattisgarh,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charger installed as on 01-01-2025,30,RS_Session_267_AU_581_C_i.csv
7,Delhi,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charger installed as on 01-01-2025,41,RS_Session_267_AU_581_C_i.csv
8,Goa,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charger installed as on 01-01-2025,9,RS_Session_267_AU_581_C_i.csv
9,Gujarat,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charger installed as on 01-01-2025,312,RS_Session_267_AU_581_C_i.csv
10,Haryana,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charger installed as on 01-01-2025,366,RS_Session_267_AU_581_C_i.csv
11,Himachal Pradesh,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charger installed as on 01-01-2025,21,RS_Session_267_AU_581_C_i.csv
12,Jammu and Kashmir,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charger installed as on 01-01-2025,23,RS_Session_267_AU_581_C_i.csv
13,Jharkhand,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charger installed as on 01-01-2025,116,RS_Session_267_AU_581_C_i.csv
14,Karnataka,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charger installed as on 01-01-2025,370,RS_Session_267_AU_581_C_i.csv
15,Kerala,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charger installed as on 01-01-2025,208,RS_Session_267_AU_581_C_i.csv
16,Ladakh,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charger installed as on 01-01-2025,0,RS_Session_267_AU_581_C_i.csv
17,Lakshadweep,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charger installed as on 01-01-2025,0,RS_Session_267_AU_581_C_i.csv
18,Madhya Pradesh,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charger installed as on 01-01-2025,154,RS_Session_267_AU_581_C_i.csv
19,Maharashtra,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charger installed as on 01-01-2025,431,RS_Session_267_AU_581_C_i.csv
20,Manipur,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charger installed as on 01-01-2025,8,RS_Session_267_AU_581_C_i.csv
21,Meghalaya,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charger installed as on 01-01-2025,25,RS_Session_267_AU_581_C_i.csv
22,Mizoram,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charger installed as on 01-01-2025,2,RS_Session_267_AU_581_C_i.csv
23,Nagaland,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charger installed as on 01-01-2025,10,RS_Session_267_AU_581_C_i.csv
24,Odisha,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charger installed as on 01-01-2025,114,RS_Session_267_AU_581_C_i.csv
25,Puducherry,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charger installed as on 01-01-2025,7,RS_Session_267_AU_581_C_i.csv
26,Punjab,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charger installed as on 01-01-2025,151,RS_Session_267_AU_581_C_i.csv
27,Rajasthan,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charger installed as on 01-01-2025,351,RS_Session_267_AU_581_C_i.csv
28,Sikkim,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charger installed as on 01-01-2025,1,RS_Session_267_AU_581_C_i.csv
29,Tamil Nadu,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charger installed as on 01-01-2025,444,RS_Session_267_AU_581_C_i.csv
30,Telangana,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charger installed as on 01-01-2025,238,RS_Session_267_AU_581_C_i.csv
31,Tripura,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charger installed as on 01-01-2025,1,RS_Session_267_AU_581_C_i.csv
32,Uttar Pradesh,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charger installed as on 01-01-2025,269,RS_Session_267_AU_581_C_i.csv
33,Dadra and Nagar Haveli and Daman and Diu,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charger installed as on 01-01-2025,3,RS_Session_267_AU_581_C_i.csv
34,Uttarakhand,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charger installed as on 01-01-2025,41,RS_Session_267_AU_581_C_i.csv
35,West Bengal,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charger installed as on 01-01-2025,280,RS_Session_267_AU_581_C_i.csv
36,Andaman and Nicobar Islands,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charging Stations energized as on 01-01-2025,0,RS_Session_267_AU_581_C_i.csv
37,Andhra Pradesh,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charging Stations energized as on 01-01-2025,20,RS_Session_267_AU_581_C_i.csv
38,Arunachal Pradesh,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charging Stations energized as on 01-01-2025,0,RS_Session_267_AU_581_C_i.csv
39,Assam,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charging Stations energized as on 01-01-2025,2,RS_Session_267_AU_581_C_i.csv
40,Bihar,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charging Stations energized as on 01-01-2025,2,RS_Session_267_AU_581_C_i.csv
41,Chandigarh,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charging Stations energized as on 01-01-2025,0,RS_Session_267_AU_581_C_i.csv
42,Chhattisgarh,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charging Stations energized as on 01-01-2025,1,RS_Session_267_AU_581_C_i.csv
43,Delhi,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charging Stations energized as on 01-01-2025,5,RS_Session_267_AU_581_C_i.csv
44,Goa,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charging Stations energized as on 01-01-2025,0,RS_Session_267_AU_581_C_i.csv
45,Gujarat,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charging Stations energized as on 01-01-2025,50,RS_Session_267_AU_581_C_i.csv
46,Haryana,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charging Stations energized as on 01-01-2025,3,RS_Session_267_AU_581_C_i.csv
47,Himachal Pradesh,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charging Stations energized as on 01-01-2025,0,RS_Session_267_AU_581_C_i.csv
48,Jammu and Kashmir,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charging Stations energized as on 01-01-2025,0,RS_Session_267_AU_581_C_i.csv
49,Jharkhand,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charging Stations energized as on 01-01-2025,0,RS_Session_267_AU_581_C_i.csv
50,Karnataka,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charging Stations energized as on 01-01-2025,3,RS_Session_267_AU_581_C_i.csv
51,Kerala,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charging Stations energized as on 01-01-2025,0,RS_Session_267_AU_581_C_i.csv
52,Ladakh,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charging Stations energized as on 01-01-2025,0,RS_Session_267_AU_581_C_i.csv
53,Lakshadweep,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charging Stations energized as on 01-01-2025,0,RS_Session_267_AU_581_C_i.csv
54,Madhya Pradesh,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charging Stations energized as on 01-01-2025,6,RS_Session_267_AU_581_C_i.csv
55,Maharashtra,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charging Stations energized as on 01-01-2025,121,RS_Session_267_AU_581_C_i.csv
56,Manipur,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charging Stations energized as on 01-01-2025,0,RS_Session_267_AU_581_C_i.csv
57,Meghalaya,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charging Stations energized as on 01-01-2025,0,RS_Session_267_AU_581_C_i.csv
58,Mizoram,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charging Stations energized as on 01-01-2025,0,RS_Session_267_AU_581_C_i.csv
59,Nagaland,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charging Stations energized as on 01-01-2025,0,RS_Session_267_AU_581_C_i.csv
60,Odisha,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charging Stations energized as on 01-01-2025,0,RS_Session_267_AU_581_C_i.csv
61,Puducherry,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charging Stations energized as on 01-01-2025,1,RS_Session_267_AU_581_C_i.csv
62,Punjab,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charging Stations energized as on 01-01-2025,2,RS_Session_267_AU_581_C_i.csv
63,Rajasthan,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charging Stations energized as on 01-01-2025,7,RS_Session_267_AU_581_C_i.csv
64,Sikkim,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charging Stations energized as on 01-01-2025,0,RS_Session_267_AU_581_C_i.csv
65,Tamil Nadu,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charging Stations energized as on 01-01-2025,6,RS_Session_267_AU_581_C_i.csv
66,Telangana,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charging Stations energized as on 01-01-2025,1,RS_Session_267_AU_581_C_i.csv
67,Tripura,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charging Stations energized as on 01-01-2025,0,RS_Session_267_AU_581_C_i.csv
68,Uttar Pradesh,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charging Stations energized as on 01-01-2025,10,RS_Session_267_AU_581_C_i.csv
69,Dadra and Nagar Haveli and Daman and Diu,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charging Stations energized as on 01-01-2025,0,RS_Session_267_AU_581_C_i.csv
70,Uttarakhand,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charging Stations energized as on 01-01-2025,4,RS_Session_267_AU_581_C_i.csv
71,West Bengal,EV Charging Stations under FAME-II Subsidy Scheme - No. of EV Charging Stations energized as on 01-01-2025,7,RS_Session_267_AU_581_C_i.csv
72,Andaman and Nicobar Islands,Total No. of EV charging stations installed by OMCs from their own funds as on 01-01-2025,6,RS_Session_267_AU_581_C_i.csv
73,Andhra Pradesh,Total No. of EV charging stations installed by OMCs from their own funds as on 01-01-2025,912,RS_Session_267_AU_581_C_i.csv
74,Arunachal Pradesh,Total No. of EV charging stations installed by OMCs from their own funds as on 01-01-2025,52,RS_Session_267_AU_581_C_i.csv
75,Assam,Total No. of EV charging stations installed by OMCs from their own funds as on 01-01-2025,448,RS_Session_267_AU_581_C_i.csv
76,Bihar,Total No. of EV charging stations installed by OMCs from their own funds as on 01-01-2025,517,RS_Session_267_AU_581_C_i.csv
77,Chandigarh,Total No. of EV charging stations installed by OMCs from their own funds as on 01-01-2025,23,RS_Session_267_AU_581_C_i.csv
78,Chhattisgarh,Total No. of EV charging stations installed by OMCs from their own funds as on 01-01-2025,498,RS_Session_267_AU_581_C_i.csv
79,Delhi,Total No. of EV charging stations installed by OMCs from their own funds as on 01-01-2025,316,RS_Session_267_AU_581_C_i.csv
80,Goa,Total No. of EV charging stations installed by OMCs from their own funds as on 01-01-2025,70,RS_Session_267_AU_581_C_i.csv
81,Gujarat,Total No. of EV charging stations installed by OMCs from their own funds as on 01-01-2025,1104,RS_Session_267_AU_581_C_i.csv
82,Haryana,Total No. of EV charging stations installed by OMCs from their own funds as on 01-01-2025,1068,RS_Session_267_AU_581_C_i.csv
83,Himachal Pradesh,Total No. of EV charging stations installed by OMCs from their own funds as on 01-01-2025,136,RS_Session_267_AU_581_C_i.csv
84,Jammu and Kashmir,Total No. of EV charging stations installed by OMCs from their own funds as on 01-01-2025,170,RS_Session_267_AU_581_C_i.csv
85,Jharkhand,Total No. of EV charging stations installed by OMCs from their own funds as on 01-01-2025,349,RS_Session_267_AU_581_C_i.csv
86,Karnataka,Total No. of EV charging stations installed by OMCs from their own funds as on 01-01-2025,1516,RS_Session_267_AU_581_C_i.csv
87,Kerala,Total No. of EV charging stations installed by OMCs from their own funds as on 01-01-2025,679,RS_Session_267_AU_581_C_i.csv
88,Ladakh,Total No. of EV charging stations installed by OMCs from their own funds as on 01-01-2025,11,RS_Session_267_AU_581_C_i.csv
89,Lakshadweep,Total No. of EV charging stations installed by OMCs from their own funds as on 01-01-2025,1,RS_Session_267_AU_581_C_i.csv
90,Madhya Pradesh,Total No. of EV charging stations installed by OMCs from their own funds as on 01-01-2025,1114,RS_Session_267_AU_581_C_i.csv
91,Maharashtra,Total No. of EV charging stations installed by OMCs from their own funds as on 01-01-2025,1595,RS_Session_267_AU_581_C_i.csv
92,Manipur,Total No. of EV charging stations installed by OMCs from their own funds as on 01-01-2025,57,RS_Session_267_AU_581_C_i.csv
93,Meghalaya,Total No. of EV charging stations installed by OMCs from their own funds as on 01-01-2025,54,RS_Session_267_AU_581_C_i.csv
94,Mizoram,Total No. of EV charging stations installed by OMCs from their own funds as on 01-01-2025,16,RS_Session_267_AU_581_C_i.csv
95,Nagaland,Total No. of EV charging stations installed by OMCs from their own funds as on 01-01-2025,41,RS_Session_267_AU_581_C_i.csv
96,Odisha,Total No. of EV charging stations installed by OMCs from their own funds as on 01-01-2025,661,RS_Session_267_AU_581_C_i.csv
97,Puducherry,Total No. of EV charging stations installed by OMCs from their own funds as on 01-01-2025,27,RS_Session_267_AU_581_C_i.csv
98,Punjab,Total No. of EV charging stations installed by OMCs from their own funds as on 01-01-2025,828,RS_Session_267_AU_581_C_i.csv
99,Rajasthan,Total No. of EV charging stations installed by OMCs from their own funds as on 01-01-2025,1482,RS_Session_267_AU_581_C_i.csv
100,Sikkim,Total No. of EV charging stations installed by OMCs from their own funds as on 01-01-2025,12,RS_Session_267_AU_581_C_i.csv
101,Tamil Nadu,Total No. of EV charging stations installed by OMCs from their own funds as on 01-01-2025,1448,RS_Session_267_AU_581_C_i.csv
102,Telangana,Total No. of EV charging stations installed by OMCs from their own funds as on 01-01-2025,1051,RS_Session_267_AU_581_C_i.csv
103,Tripura,Total No. of EV charging stations installed by OMCs from their own funds as on 01-01-2025,55,RS_Session_267_AU_581_C_i.csv
104,Uttar Pradesh,Total No. of EV charging stations installed by OMCs from their own funds as on 01-01-2025,2561,RS_Session_267_AU_581_C_i.csv
105,Dadra and Nagar Haveli and Daman and Diu,Total No. of EV charging stations installed by OMCs from their own funds as on 01-01-2025,12,RS_Session_267_AU_581_C_i.csv
106,Uttarakhand,Total No. of EV charging stations installed by OMCs from their own funds as on 01-01-2025,212,RS_Session_267_AU_581_C_i.csv
107,West Bengal,Total No. of EV charging stations installed by OMCs from their own funds as on 01-01-2025,933,RS_Session_267_AU_581_C_i.csv

In [26]:
df_city = load_and_clean("RS_Session_256_AU_2673_1.csv")
df_city = df_city.rename(columns={"City/Highway": "location", "Charging Stations": "count"})
df_city["source_file"] = "RS_Session_256_AU_2673_1.csv"

master_charging_city_highway = df_city[~df_city["location"].astype(str).str.contains("Total", case=False, na=False)]
master_charging_city_highway.info()
master_charging_city_highway

<class 'pandas.core.frame.DataFrame'>
Index: 14 entries, 0 to 14
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Category     14 non-null     object
 1   location     14 non-null     object
 2   count        14 non-null     int64
 3   source_file  14 non-null     object
dtypes: int64(1), object(3)
memory usage: 560.0+ bytes

   Category              location  count                   source_file
0      City            Chandigarh     48  RS_Session_256_AU_2673_1.csv
1      City                 Delhi     94  RS_Session_256_AU_2673_1.csv
2      City                Jaipur     49  RS_Session_256_AU_2673_1.csv
3      City                B'Lore     60  RS_Session_256_AU_2673_1.csv
4      City                Ranchi     30  RS_Session_256_AU_2673_1.csv
5      City               Lucknow      1  RS_Session_256_AU_2673_1.csv
6      City                   Goa     30  RS_Session_256_AU_2673_1.csv
7      City             Hyderabad     57  RS_Session_256_AU_2673_1.csv
8      City                  Agra     15  RS_Session_256_AU_2673_1.csv
9      City                Shimla      9  RS_Session_256_AU_2673_1.csv
11  Highway     Delhi -Chandigarh     24  RS_Session_256_AU_2673_1.csv
12  Highway              Mum-Pune     16  RS_Session_256_AU_2673_1.csv
13  Highway   Delhi- Jaipur- Agra     31  RS_Session_256_AU_2673_1.csv
14  Highway  Jaipur-Delhi Highway      9  RS_Session_256_AU_2673_1.csv

In [27]:
df_exp = load_and_clean("RS_Session_256_AU_2673_2.ii_.csv")
df_exp = df_exp.rename(columns={"Expressways/Highways": "route", "EV Charging Stations Sanctioned": "count"})
df_exp["source_file"] = "RS_Session_256_AU_2673_2.ii_.csv"

master_charging_expressway = df_exp[~df_exp["route"].astype(str).str.contains("Total", case=False, na=False)]
master_charging_expressway.info()
master_charging_expressway

<class 'pandas.core.frame.DataFrame'>
Index: 25 entries, 0 to 24
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Sl. No       25 non-null     object
 1   Category     25 non-null     object
 2   route        25 non-null     object
 3   count        25 non-null     int64
 4   source_file  25 non-null     object
dtypes: int64(1), object(4)
memory usage: 1.2+ KB

,Sl. No,Category,route,count,source_file
0,1,Expressways,Mumbai - Pune,10,RS_Session_256_AU_2673_2.ii_.csv
1,2,Expressways,Ahmadabad - Vadodara,10,RS_Session_256_AU_2673_2.ii_.csv
2,3,Expressways,Delhi Agra Yamuna,20,RS_Session_256_AU_2673_2.ii_.csv
3,4,Expressways,Bengaluru Mysore,14,RS_Session_256_AU_2673_2.ii_.csv
4,5,Expressways,Bangaluru-Chennai,30,RS_Session_256_AU_2673_2.ii_.csv
5,6,Expressways,Surat-Mumbai,30,RS_Session_256_AU_2673_2.ii_.csv
6,7,Expressways,Agra-Lucknow,40,RS_Session_256_AU_2673_2.ii_.csv
7,8,Expressways,Eastern Peripheral (A),14,RS_Session_256_AU_2673_2.ii_.csv
8,9,Expressways,Hyderabad ORR,16,RS_Session_256_AU_2673_2.ii_.csv
9,1,Highways,Delhi - Srinagar,80,RS_Session_256_AU_2673_2.ii_.csv
10,2,Highways,Delhi  Kolkata,160,RS_Session_256_AU_2673_2.ii_.csv
11,3,Highways,Agra - Nagpur,80,RS_Session_256_AU_2673_2.ii_.csv
12,4,Highways,Meerut to GangotriDham,44,RS_Session_256_AU_2673_2.ii_.csv
13,5,Highways,Mumbai - Delhi,124,RS_Session_256_AU_2673_2.ii_.csv
14,6,Highways,Mumbai-Panaji,60,RS_Session_256_AU_2673_2.ii_.csv
15,7,Highways,Mumbai - Nagpur,70,RS_Session_256_AU_2673_2.ii_.csv
16,8,Highways,Mumbai - Bengaluru,100,RS_Session_256_AU_2673_2.ii_.csv
17,9,Highways,Kolkata - Bhubaneswar,44,RS_Session_256_AU_2673_2.ii_.csv
18,10,Highways,Kolkata - Nagpur,120,RS_Session_256_AU_2673_2.ii_.csv
19,11,Highways,Kolkata - Gangtok,76,RS_Session_256_AU_2673_2.ii_.csv
20,12,Highways,Chennai-Bhubaneswar,120,RS_Session_256_AU_2673_2.ii_.csv
21,13,Highways,Chennai - Trivendram,74,RS_Session_256_AU_2673_2.ii_.csv
22,14,Highways,Chennai-Ballary,62,RS_Session_256_AU_2673_2.ii_.csv
23,15,Highways,Chennai - Nagpur,114,RS_Session_256_AU_2673_2.ii_.csv
24,16,Highways,Mangaldai - Wakro,64,RS_Session_256_AU_2673_2.ii_.csv

In [28]:
df_org = load_and_clean("RS_Session_259_AU_2474_A.csv")
df_org["source_file"] = "RS_Session_259_AU_2474_A.csv"
master_charging_by_organization = df_org
master_charging_by_organization.info()
master_charging_by_organization

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Charging Stations details  3 non-null      object
 1   Organization               3 non-null      object
 2   Sanctioned                 3 non-null      int64
 3   Installed                  3 non-null      int64
 4   source_file                3 non-null      object
dtypes: int64(2), object(3)
memory usage: 252.0+ bytes

,Charging Stations details,Organization,Sanctioned,Installed,source_file
0,"Solar Based Charging Infrastructure for EVs in NCR by REIL, Jaipur","REIL, Jaipur",3,3,RS_Session_259_AU_2474_A.csv
1,Solar Grid Hybrid and Grid powered Charging Station along Delhi-Jaipur-Agra Highway,REIL,25,25,RS_Session_259_AU_2474_A.csv
2,Solar Based Chargers (20 locations) along Delhi Chandigarh Highway,BHEL,20,20,RS_Session_259_AU_2474_A.csv

In [29]:
df_nh = load_and_clean("RS_Session_259_AU_2837_B.csv")
df_nh = df_nh.rename(columns={"National Highway": "highway", "No. of Operational PCS": "count"})
df_nh["source_file"] = "RS_Session_259_AU_2837_B.csv"

master_charging_national_highway = df_nh[~df_nh["highway"].astype(str).str.contains("Total", case=False, na=False)]
master_charging_national_highway.info()
master_charging_national_highway

<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 0 to 89
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   highway      90 non-null     object
 1   count        90 non-null     int64
 2   source_file  90 non-null     object
dtypes: int64(1), object(2)
memory usage: 2.8+ KB

                  highway  count                   source_file
0     National Highway-10      1  RS_Session_259_AU_2837_B.csv
1     National Highway-11      3  RS_Session_259_AU_2837_B.csv
2    National Highway-128      1  RS_Session_259_AU_2837_B.csv
3     National Highway-13      3  RS_Session_259_AU_2837_B.csv
4    National Highway-130      1  RS_Session_259_AU_2837_B.csv
5   National Highway-130A      2  RS_Session_259_AU_2837_B.csv
6   National Highway-130B      2  RS_Session_259_AU_2837_B.csv
7   National Highway-130C      2  RS_Session_259_AU_2837_B.csv
8    National Highway-135      2  RS_Session_259_AU_2837_B.csv
9    National Highway-143      2  RS_Session_259_AU_2837_B.csv
10  National Highway-148A      2  RS_Session_259_AU_2837_B.csv
11   National Highway-149      2  RS_Session_259_AU_2837_B.csv
12    National Highway-15      4  RS_Session_259_AU_2837_B.csv
13  National Highway-150A      2  RS_Session_259_AU_2837_B.csv
14    National Highway-16     37  RS_Session_259_AU_2837_B.csv
15  National Highway-161A      2  RS_Session_259_AU_2837_B.csv
16   National Highway-163      9  RS_Session_259_AU_2837_B.csv
17   National Highway-167      3  RS_Session_259_AU_2837_B.csv
18  National Highway-167A      1  RS_Session_259_AU_2837_B.csv
19  National Highway-169A      2  RS_Session_259_AU_2837_B.csv
20    National Highway-19      5  RS_Session_259_AU_2837_B.csv
21     National Highway-2      5  RS_Session_259_AU_2837_B.csv
22    National Highway-20      2  RS_Session_259_AU_2837_B.csv
23    National Highway-21      1  RS_Session_259_AU_2837_B.csv
24    National Highway-22      3  RS_Session_259_AU_2837_B.csv
25   National Highway-228      2  RS_Session_259_AU_2837_B.csv
26    National Highway-24      7  RS_Session_259_AU_2837_B.csv
27   National Highway-254      2  RS_Session_259_AU_2837_B.csv
28    National Highway-26      4  RS_Session_259_AU_2837_B.csv
29    National Highway-27      2  RS_Session_259_AU_2837_B.csv
30   National Highway-275      2  RS_Session_259_AU_2837_B.csv
31    National Highway-28      3  RS_Session_259_AU_2837_B.csv
32    National Highway-29      1  RS_Session_259_AU_2837_B.csv
33     National Highway-3      4  RS_Session_259_AU_2837_B.csv
34    National Highway-30     12  RS_Session_259_AU_2837_B.csv
35   National Highway-305      1  RS_Session_259_AU_2837_B.csv
36   National Highway-307      5  RS_Session_259_AU_2837_B.csv
37   National Highway-309      3  RS_Session_259_AU_2837_B.csv
38    National Highway-31      1  RS_Session_259_AU_2837_B.csv
39   National Highway-313      1  RS_Session_259_AU_2837_B.csv
40    National Highway-32      1  RS_Session_259_AU_2837_B.csv
41  National Highway-320D      1  RS_Session_259_AU_2837_B.csv
42   National Highway-334      6  RS_Session_259_AU_2837_B.csv
43    National Highway-34      8  RS_Session_259_AU_2837_B.csv
44   National Highway-346      2  RS_Session_259_AU_2837_B.csv
45   National Highway-347      2  RS_Session_259_AU_2837_B.csv
46  National Highway-347B      2  RS_Session_259_AU_2837_B.csv
47    National Highway-35      1  RS_Session_259_AU_2837_B.csv
48   National Highway-353      2  RS_Session_259_AU_2837_B.csv
49   National Highway-365      1  RS_Session_259_AU_2837_B.csv
50    National Highway-39     10  RS_Session_259_AU_2837_B.csv
51    National Highway-40      1  RS_Session_259_AU_2837_B.csv
52    National Highway-43      2  RS_Session_259_AU_2837_B.csv
53    National Highway-44     39  RS_Session_259_AU_2837_B.csv
54    National Highway-46      2  RS_Session_259_AU_2837_B.csv
55    National Highway-47      2  RS_Session_259_AU_2837_B.csv
56    National Highway-48     11  RS_Session_259_AU_2837_B.csv
57    National Highway-49      2  RS_Session_259_AU_2837_B.csv
58     National Highway-5      6  RS_Session_259_AU_2837_B.csv
59    National Highway-50      3  RS_Session_259_AU_2837_B.csv
60   National Highway-507      1  RS_Session_259_AU_2837_B.csv
61   National Highway-515      4  RS_Session_259_AU_2837_B.csv
62    National Highway-52      6  RS_Session_259_AU_2837_B.csv
63    National Highway-53      5  RS_Session_259_AU_2837_B.csv
64   National Highway-539     14  RS_Session_259_AU_2837_B.csv
65    National Highway-55      9  RS_Session_259_AU_2837_B.csv
66   National Highway-565      1  RS_Session_259_AU_2837_B.csv
67    National Highway-58     10  RS_Session_259_AU_2837_B.csv
68    National Highway-59      2  RS_Session_259_AU_2837_B.csv
69     National Highway-6      8  RS_Session_259_AU_2837_B.csv
70    National Highway-63      1  RS_Session_259_AU_2837_B.csv
71    National Highway-64      2  RS_Session_259_AU_2837_B.csv
72   National Highway-648      2  RS_Session_259_AU_2837_B.csv
73    National Highway-65     22  RS_Session_259_AU_2837_B.csv
74    National Highway-66      8  RS_Session_259_AU_2837_B.csv
75    National Highway-67      4  RS_Session_259_AU_2837_B.csv
76     National Highway-7     18  RS_Session_259_AU_2837_B.csv
77   National Highway-716      1  RS_Session_259_AU_2837_B.csv
78  National Highway-727A      1  RS_Session_259_AU_2837_B.csv
79   National Highway-730      4  RS_Session_259_AU_2837_B.csv
80   National Highway-731      2  RS_Session_259_AU_2837_B.csv
81    National Highway-75      3  RS_Session_259_AU_2837_B.csv
82  National Highway-752B      2  RS_Session_259_AU_2837_B.csv
83  National Highway-752C      2  RS_Session_259_AU_2837_B.csv
84   National Highway-765      1  RS_Session_259_AU_2837_B.csv
85   National Highway-766      2  RS_Session_259_AU_2837_B.csv
86     National Highway-8     12  RS_Session_259_AU_2837_B.csv
87    National Highway-86      2  RS_Session_259_AU_2837_B.csv
88     National Highway-9     15  RS_Session_259_AU_2837_B.csv
89  National Highway-948A      2  RS_Session_259_AU_2837_B.csv

In [30]:
df_dist = load_and_clean("RS_Session_266_AU_2960_C_to_D_i.csv")
df_dist = df_dist.rename(columns={"No. of EVPCS": "count"})
df_dist["source_file"] = "RS_Session_266_AU_2960_C_to_D_i.csv"

master_charging_district = df_dist[~df_dist["District"].astype(str).str.contains("Total", case=False, na=False)]
master_charging_district.info()
master_charging_district

<class 'pandas.core.frame.DataFrame'>
Index: 31 entries, 0 to 30
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Sl. No.      31 non-null     object
 1   District     31 non-null     object
 2   count        31 non-null     int64
 3   source_file  31 non-null     object
dtypes: int64(1), object(3)
memory usage: 1.2+ KB

,Sl. No.,District,count,source_file
0,1,Raipur,57,RS_Session_266_AU_2960_C_to_D_i.csv
1,2,Bilaspur,28,RS_Session_266_AU_2960_C_to_D_i.csv
2,3,Rajnandgaon,24,RS_Session_266_AU_2960_C_to_D_i.csv
3,4,Durg,19,RS_Session_266_AU_2960_C_to_D_i.csv
4,5,Surguja,15,RS_Session_266_AU_2960_C_to_D_i.csv
5,6,Janjgir-Champa,13,RS_Session_266_AU_2960_C_to_D_i.csv
6,7,Korba,11,RS_Session_266_AU_2960_C_to_D_i.csv
7,8,Mahasamund,10,RS_Session_266_AU_2960_C_to_D_i.csv
8,9,Balod,9,RS_Session_266_AU_2960_C_to_D_i.csv
9,10,Dhamtari,9,RS_Session_266_AU_2960_C_to_D_i.csv
10,11,Jashpur,9,RS_Session_266_AU_2960_C_to_D_i.csv
11,12,Raigarh,9,RS_Session_266_AU_2960_C_to_D_i.csv
12,13,Bemetara,8,RS_Session_266_AU_2960_C_to_D_i.csv
13,14,Mungeli,6,RS_Session_266_AU_2960_C_to_D_i.csv
14,15,Surajpur,6,RS_Session_266_AU_2960_C_to_D_i.csv
15,16,Balodabazar-Bhatapara,5,RS_Session_266_AU_2960_C_to_D_i.csv
16,17,Balrampur,5,RS_Session_266_AU_2960_C_to_D_i.csv
17,18,Uttar Bastar Kanker,5,RS_Session_266_AU_2960_C_to_D_i.csv
18,19,Bastar,4,RS_Session_266_AU_2960_C_to_D_i.csv
19,20,Korea,3,RS_Session_266_AU_2960_C_to_D_i.csv
20,21,Dakshin Bastar Dantewada,2,RS_Session_266_AU_2960_C_to_D_i.csv
21,22,Kabirdham (Kawardha),2,RS_Session_266_AU_2960_C_to_D_i.csv
22,23,Kondagaon,2,RS_Session_266_AU_2960_C_to_D_i.csv
23,24,Narayanpur,2,RS_Session_266_AU_2960_C_to_D_i.csv
24,25,Sukma,2,RS_Session_266_AU_2960_C_to_D_i.csv
25,26,Bijapur,1,RS_Session_266_AU_2960_C_to_D_i.csv
26,27,Gariyaband,1,RS_Session_266_AU_2960_C_to_D_i.csv
27,28,Kabeerdham,1,RS_Session_266_AU_2960_C_to_D_i.csv
28,29,Kanker,1,RS_Session_266_AU_2960_C_to_D_i.csv
29,30,Manendragarh Chirmiri Bharatpur,1,RS_Session_266_AU_2960_C_to_D_i.csv
30,31,Sarangarh-Bilaigarh,1,RS_Session_266_AU_2960_C_to_D_i.csv

## Insights: Charging Infrastructure

- Charging stations are extremely concentrated in a handful of states —
  Karnataka (5,765 EVPCS) and Maharashtra (3,728) dominate, while many
  smaller states/UTs have single digits.
- Delhi stands out for *operational* public charging stations specifically
  (1,886+) even though it's not top of the EVPCS list — worth checking why
  in analysis (different metric/date, or genuinely different infra type).
- OMC (oil company)-funded stations are a much bigger number than
  FAME-II subsidized ones in most states (e.g. UP: 2,561 OMC-funded vs.
  269 FAME-II installed) — suggests private/OMC investment is outpacing
  government subsidy rollout.
- FAME-I data mixes actual states with named highway corridors in the same
  column — needs separating before any state-level comparison.
- Two files (429_1 and 91_1) turned out to be exact duplicates — a reminder
  that government data releases can overlap.

In [31]:
for f in theme_groups["scheme_budget_and_subsidy"]:
    df = load_and_clean(f)
    print(f"\n{f} — shape {df.shape}")
    display(df.head(2))

RS_Session_254_AU_1496.A.csv — shape (7, 3)

  Financial Year  Fund Allocation  Fund Utilization
0        2015-16             75.0              75.0
1        2016-17            144.0             144.0

RS_Session_258_AU_2037_A.csv — shape (4, 4)

,Sl. No.,Financial Year,Budget Allocation,Fund Utilization as on 30.11.2022
0,1,2019-2020,500.00,500.00
1,2,2020-2021,318.36,318.36

RS_Session_258_AU_429_B.csv — shape (4, 3)

   S.No.      Category Amount (in Rs. Crore)
0      1  e-2 Wheelers       2464.27 approx.
1      2  e-3 Wheelers        351.21 approx.

RS_Session_259_AU_2028_A.csv — shape (4, 3)

  Financial Year  Budget Allocation  Fund Utilization as on 30-11-2022
0      2019-2020             500.00                             500.00
1      2020-2021             318.36                             318.36

RS_Session_259_AU_2836_A.csv — shape (5, 3)

,Category,Vehicles to be Supported (in Nos),Actual Vehicles supported (in Nos)
0,e-2W,1000000,792529
1,e-3W,500000,81172

RS_Session_259_AU_3477_A_to_D.csv — shape (5, 3)

,Category,Vehicles to be Supported (in No.),Actual Vehicles Supported (in No.)
0,e-2W,1000000,792529
1,e-3W,500000,81172

RS_Session_263_AU_105_A.csv — shape (5, 3)

  Financial Year  Budget Allocation  Fund Utilization as on 31-01-2024
0        2019-20             500.00                             500.00
1        2020-21             318.36                             318.36

RS_Session_266_AS_217_4.csv — shape (6, 2)

     Years  Energy Requirement
0  2024-25                7170
1  2025-26               12160

RS_Session_266_AU_553_A_to_B.csv — shape (6, 3)

,Sl. No.,Electric Vehicle segment supported under PM E-DRIVE Scheme,Budget Allocated for the vehicle segment
0,1,Registered e-2Wheelers,1772
1,2,Registered e-3 Wheelers - e-Rickshaws and e-Cart,192

RS_Session_267_AU_580_A.csv — shape (4, 3)

  Sl. No. EV Segment  Total No. of EVs supported
0       1  2 wheeler                     1428009
1       2  3 wheeler                      164180

In [32]:
df_2836 = load_and_clean("RS_Session_259_AU_2836_A.csv")
df_3477 = load_and_clean("RS_Session_259_AU_3477_A_to_D.csv")
print(df_2836.equals(df_3477))
print(df_2836)
print(df_3477)

False
  Category  Vehicles to be Supported (in Nos)  \
0     e-2W                            1000000
1     e-3W                             500000
2     e-4W                              55000
3  e-Buses                               7090
4    Total                            1562090

   Actual Vehicles supported (in Nos)
0                              792529
1                               81172
2                                6831
3                                2435
4                              882967
  Category  Vehicles to be Supported (in No.)  \
0     e-2W                            1000000
1     e-3W                             500000
2     e-4W                              55000
3  e-Buses                               7090
4    Total                            1562090

   Actual Vehicles Supported (in No.)
0                              792529
1                               81172
2                                6831
3                                2435
4                              882967

In [34]:
group_a_files = [
    "RS_Session_254_AU_1496.A.csv",
    "RS_Session_258_AU_2037_A.csv",
    "RS_Session_259_AU_2028_A.csv",
    "RS_Session_263_AU_105_A.csv",
]

frames = []
for f in group_a_files:
    df = load_and_clean(f)
    util_col = [c for c in df.columns if "Fund Utilization" in c][0]
    alloc_col = "Budget Allocation" if "Budget Allocation" in df.columns else "Fund Allocation"
    df = df.rename(columns={"Financial Year": "financial_year",
                             alloc_col: "budget_allocation",
                             util_col: "fund_utilization"})
    df["source_file"] = f
    frames.append(df[["financial_year", "budget_allocation", "fund_utilization", "source_file"]])

master_scheme_budget_by_year = pd.concat(frames, ignore_index=True, sort=False)
master_scheme_budget_by_year.info()
master_scheme_budget_by_year

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   financial_year     20 non-null     object
 1   budget_allocation  20 non-null     float64
 2   fund_utilization   20 non-null     float64
 3   source_file        20 non-null     object
dtypes: float64(2), object(2)
memory usage: 772.0+ bytes

,financial_year,budget_allocation,fund_utilization,source_file
0,2015-16,75.00,75.00,RS_Session_254_AU_1496.A.csv
1,2016-17,144.00,144.00,RS_Session_254_AU_1496.A.csv
2,2017-18,165.00,165.00,RS_Session_254_AU_1496.A.csv
3,2018-19,145.00,145.00,RS_Session_254_AU_1496.A.csv
4,2019-20,500.00,500.00,RS_Session_254_AU_1496.A.csv
5,2020-21,318.36,318.36,RS_Session_254_AU_1496.A.csv
6,2021-22,756.66,53.27,RS_Session_254_AU_1496.A.csv
7,2019-2020,500.00,500.00,RS_Session_258_AU_2037_A.csv
8,2020-2021,318.36,318.36,RS_Session_258_AU_2037_A.csv
9,2021-2022,800.00,800.00,RS_Session_258_AU_2037_A.csv
10,2022-2023,2903.08,1128.45,RS_Session_258_AU_2037_A.csv
11,2019-2020,500.00,500.00,RS_Session_259_AU_2028_A.csv
12,2020-2021,318.36,318.36,RS_Session_259_AU_2028_A.csv
13,2021-2022,800.00,800.00,RS_Session_259_AU_2028_A.csv
14,2022-2023,2897.84,1382.90,RS_Session_259_AU_2028_A.csv
15,2019-20,500.00,500.00,RS_Session_263_AU_105_A.csv
16,2020-21,318.36,318.36,RS_Session_263_AU_105_A.csv
17,2021-22,800.00,800.00,RS_Session_263_AU_105_A.csv
18,2022-23,2897.84,2402.51,RS_Session_263_AU_105_A.csv
19,2023-24,5171.97,1980.83,RS_Session_263_AU_105_A.csv

In [35]:
df_amount = load_and_clean("RS_Session_258_AU_429_B.csv")
df_amount = df_amount.rename(columns={"Amount (in Rs. Crore)": "amount_rs_crore"})
df_amount["amount_rs_crore"] = clean_numeric_column(df_amount["amount_rs_crore"])
df_amount["source_file"] = "RS_Session_258_AU_429_B.csv"

master_scheme_subsidy_amount = df_amount
master_scheme_subsidy_amount.info()
master_scheme_subsidy_amount

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   S.No.            4 non-null      int64
 1   Category         4 non-null      object
 2   amount_rs_crore  4 non-null      float64
 3   source_file      4 non-null      object
dtypes: float64(1), int64(1), object(2)
memory usage: 260.0+ bytes

   S.No.      Category  amount_rs_crore                  source_file
0      1  e-2 Wheelers          2464.27  RS_Session_258_AU_429_B.csv
1      2  e-3 Wheelers           351.21  RS_Session_258_AU_429_B.csv
2      3  e-4 Wheelers           114.65  RS_Session_258_AU_429_B.csv
3      4       e-buses           687.93  RS_Session_258_AU_429_B.csv

In [36]:
df_targets = load_and_clean("RS_Session_259_AU_2836_A.csv")
df_targets = df_targets[~df_targets["Category"].astype(str).str.contains("Total", case=False, na=False)]
df_targets = df_targets.rename(columns={
    "Vehicles to be Supported (in Nos)": "target_vehicles",
    "Actual Vehicles supported (in Nos)": "actual_vehicles"
})
df_targets["source_file"] = "RS_Session_259_AU_2836_A.csv"
# note: RS_Session_259_AU_3477_A_to_D.csv is a duplicate of this file — excluded

master_scheme_vehicle_targets = df_targets
master_scheme_vehicle_targets.info()
master_scheme_vehicle_targets

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Category         4 non-null      object
 1   target_vehicles  4 non-null      int64
 2   actual_vehicles  4 non-null      int64
 3   source_file      4 non-null      object
dtypes: int64(2), object(2)
memory usage: 160.0+ bytes

  Category  target_vehicles  actual_vehicles                   source_file
0     e-2W          1000000           792529  RS_Session_259_AU_2836_A.csv
1     e-3W           500000            81172  RS_Session_259_AU_2836_A.csv
2     e-4W            55000             6831  RS_Session_259_AU_2836_A.csv
3  e-Buses             7090             2435  RS_Session_259_AU_2836_A.csv

In [37]:
df_energy = load_and_clean("RS_Session_266_AS_217_4.csv")
df_energy = df_energy.rename(columns={"Years": "year"})
df_energy["source_file"] = "RS_Session_266_AS_217_4.csv"

master_scheme_energy_requirement = df_energy
master_scheme_energy_requirement.info()
master_scheme_energy_requirement

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   year                6 non-null      object
 1   Energy Requirement  6 non-null      int64
 2   source_file         6 non-null      object
dtypes: int64(1), object(2)
memory usage: 276.0+ bytes

      year  Energy Requirement                  source_file
0  2024-25                7170  RS_Session_266_AS_217_4.csv
1  2025-26               12160  RS_Session_266_AS_217_4.csv
2  2026-27               18910  RS_Session_266_AS_217_4.csv
3  2027-28               27688  RS_Session_266_AS_217_4.csv
4  2028-29               38788  RS_Session_266_AS_217_4.csv
5  2029-30               52604  RS_Session_266_AS_217_4.csv

In [38]:
df_pmedrive = load_and_clean("RS_Session_266_AU_553_A_to_B.csv")
df_pmedrive = df_pmedrive.rename(columns={
    "Electric Vehicle segment supported under PM E-DRIVE Scheme": "segment",
    "Budget Allocated for the vehicle segment": "budget_allocated"
})
df_pmedrive["source_file"] = "RS_Session_266_AU_553_A_to_B.csv"

master_scheme_pmedrive_budget = df_pmedrive[["segment", "budget_allocated", "source_file"]]
master_scheme_pmedrive_budget.info()
master_scheme_pmedrive_budget

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   segment           6 non-null      object
 1   budget_allocated  6 non-null      int64
 2   source_file       6 non-null      object
dtypes: int64(1), object(2)
memory usage: 276.0+ bytes

,segment,budget_allocated,source_file
0,Registered e-2Wheelers,1772,RS_Session_266_AU_553_A_to_B.csv
1,Registered e-3 Wheelers - e-Rickshaws and e-Cart,192,RS_Session_266_AU_553_A_to_B.csv
2,Registered e-3Wheelers (L5),715,RS_Session_266_AU_553_A_to_B.csv
3,e-ambulance,500,RS_Session_266_AU_553_A_to_B.csv
4,e-trucks and other emerging EVs,500,RS_Session_266_AU_553_A_to_B.csv
5,Registered e-buses,4391,RS_Session_266_AU_553_A_to_B.csv

In [39]:
df_supported = load_and_clean("RS_Session_267_AU_580_A.csv")
df_supported = df_supported.rename(columns={
    "EV Segment": "segment",
    "Total No. of EVs supported": "evs_supported"
})
df_supported["source_file"] = "RS_Session_267_AU_580_A.csv"

master_scheme_evs_supported = df_supported[~df_supported["segment"].astype(str).str.contains("Total", case=False, na=False)]
master_scheme_evs_supported.info()
master_scheme_evs_supported

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sl. No.        3 non-null      object
 1   segment        3 non-null      object
 2   evs_supported  3 non-null      int64
 3   source_file    3 non-null      object
dtypes: int64(1), object(3)
memory usage: 120.0+ bytes

  Sl. No.    segment  evs_supported                  source_file
0       1  2 wheeler        1428009  RS_Session_267_AU_580_A.csv
1       2  3 wheeler         164180  RS_Session_267_AU_580_A.csv
2       3  4 wheeler          22548  RS_Session_267_AU_580_A.csv

## Insights: Scheme Budget & Subsidy

- Government funding for the EV scheme has scaled up dramatically over time —
  allocation rose from ₹75 crore (2015-16) to ₹5,171.97 crore (2023-24), a
  ~69x increase over 8 years.
- Fund utilization consistently lags allocation, especially in newer years —
  e.g. 2021-22 allocated ₹756.66 crore but an early snapshot shows only
  ₹53.27 crore utilized, suggesting a rollout/implementation lag rather than
  a funding shortage.
- The same financial year's utilization figure changes across successive
  Parliament questions (e.g. 2022-23 utilization reported as ₹1,128.45cr,
  then ₹1,382.90cr, then ₹2,402.51cr in later files) — this reflects
  utilization catching up over time as more of the year's activity gets
  reported, not inconsistent data. For any full-period analysis, the most
  recent snapshot per financial year should be used to avoid triple-counting.
- Subsidy uptake vs. targets shows a significant gap: only 792,529 of a
  targeted 1,000,000 e-2-wheelers were

In [40]:
for f in theme_groups["sales_by_category"]:
    df = load_and_clean(f)
    print(f"\n{f} — shape {df.shape}")
    display(df.head(2))

RS_Session_263_AU_102_A.csv — shape (5, 5)

  Sl. No.    Category    2022    2023  % Growth
0       1  2 Wheelers  631464  859376     36.09
1       2  3 Wheelers  352710  582793     65.23

RS_Session_263_AU_105_C.csv — shape (4, 3)

  Sl. No. Wheeler Type  Total No. of Vehicle
0       1    2 wheeler               1185829
1       2    3 wheeler                138639

RS_Session_260_AS_241_E.csv — shape (3, 5)

,Category,Fuel Types,Domestic Sales (MoRTH) - 2020-21,Domestic Sales (MoRTH) - 2021-22,Domestic Sales (MoRTH) - 2022-23
0,Passenger Vehicles (e-4W),EVs,5000,19000,47581
1,Three Wheelers (e-3W),EVs,88000,178000,402106

In [41]:
df_growth = load_and_clean("RS_Session_263_AU_102_A.csv")
df_growth = df_growth[~df_growth["Category"].astype(str).str.contains("Total", case=False, na=False)]
df_growth = df_growth.rename(columns={"2022": "sales_2022", "2023": "sales_2023", "% Growth": "pct_growth"})
df_growth["source_file"] = "RS_Session_263_AU_102_A.csv"

master_sales_category_growth = df_growth[["Category", "sales_2022", "sales_2023", "pct_growth", "source_file"]]
master_sales_category_growth.info()
master_sales_category_growth

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Category     4 non-null      object
 1   sales_2022   4 non-null      int64
 2   sales_2023   4 non-null      int64
 3   pct_growth   4 non-null      float64
 4   source_file  4 non-null      object
dtypes: float64(1), int64(2), object(2)
memory usage: 192.0+ bytes

,Category,sales_2022,sales_2023,pct_growth,source_file
0,2 Wheelers,631464,859376,36.09,RS_Session_263_AU_102_A.csv
1,3 Wheelers,352710,582793,65.23,RS_Session_263_AU_102_A.csv
2,Commercial Vehicles,2649,5673,114.16,RS_Session_263_AU_102_A.csv
3,Passenger Vehicles,38240,82105,114.71,RS_Session_263_AU_102_A.csv

In [42]:
df_total = load_and_clean("RS_Session_263_AU_105_C.csv")
df_total = df_total[~df_total["Wheeler Type"].astype(str).str.contains("Total", case=False, na=False)]
df_total = df_total.rename(columns={"Wheeler Type": "wheeler_type", "Total No. of Vehicle": "total_vehicles"})
df_total["source_file"] = "RS_Session_263_AU_105_C.csv"

master_sales_wheeler_totals = df_total[["wheeler_type", "total_vehicles", "source_file"]]
master_sales_wheeler_totals.info()
master_sales_wheeler_totals

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   wheeler_type    3 non-null      object
 1   total_vehicles  3 non-null      int64
 2   source_file     3 non-null      object
dtypes: int64(1), object(2)
memory usage: 96.0+ bytes

  wheeler_type  total_vehicles                  source_file
0    2 wheeler         1185829  RS_Session_263_AU_105_C.csv
1    3 wheeler          138639  RS_Session_263_AU_105_C.csv
2    4 wheeler           16991  RS_Session_263_AU_105_C.csv

In [43]:
df_domestic = load_and_clean("RS_Session_260_AS_241_E.csv")

year_cols = [c for c in df_domestic.columns if "Domestic Sales" in c]

master_sales_domestic_by_year = df_domestic.melt(
    id_vars=["Category", "Fuel Types"],
    value_vars=year_cols,
    var_name="year_label",
    value_name="domestic_sales"
)
# extract just the year part, e.g. "2020-21", from the column label
master_sales_domestic_by_year["year"] = master_sales_domestic_by_year["year_label"].str.extract(r'(\d{4}-\d{2})')
master_sales_domestic_by_year = master_sales_domestic_by_year.drop(columns=["year_label"])
master_sales_domestic_by_year["source_file"] = "RS_Session_260_AS_241_E.csv"

master_sales_domestic_by_year.info()
master_sales_domestic_by_year

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Category        9 non-null      object
 1   Fuel Types      9 non-null      object
 2   domestic_sales  9 non-null      int64
 3   year            9 non-null      object
 4   source_file     9 non-null      object
dtypes: int64(1), object(4)
memory usage: 492.0+ bytes

,Category,Fuel Types,domestic_sales,year,source_file
0,Passenger Vehicles (e-4W),EVs,5000,2020-21,RS_Session_260_AS_241_E.csv
1,Three Wheelers (e-3W),EVs,88000,2020-21,RS_Session_260_AS_241_E.csv
2,Two Wheelers (e-2W),EVs,41000,2020-21,RS_Session_260_AS_241_E.csv
3,Passenger Vehicles (e-4W),EVs,19000,2021-22,RS_Session_260_AS_241_E.csv
4,Three Wheelers (e-3W),EVs,178000,2021-22,RS_Session_260_AS_241_E.csv
5,Two Wheelers (e-2W),EVs,231000,2021-22,RS_Session_260_AS_241_E.csv
6,Passenger Vehicles (e-4W),EVs,47581,2022-23,RS_Session_260_AS_241_E.csv
7,Three Wheelers (e-3W),EVs,402106,2022-23,RS_Session_260_AS_241_E.csv
8,Two Wheelers (e-2W),EVs,728027,2022-23,RS_Session_260_AS_241_E.csv

## Insights: Sales by Vehicle Category

- Domestic EV sales grew dramatically across 2020-21 to 2022-23, but growth
  rates differ sharply by category:
  - Two-wheelers: 41,000 → 231,000 → 728,027 (~18x over 2 years) — by far
    the largest volume and fastest-growing segment.
  - Three-wheelers: 88,000 → 178,000 → 402,106 (~4.6x) — strong, steady
    growth.
  - Passenger vehicles (e-4W): 5,000 → 19,000 → 47,581 (~9.5x) — smallest
    absolute volume, though a comparable multiple of growth.
- 2022→2023 YoY growth % is highest for Commercial Vehicles (114.16%) and
  Passenger Vehicles (114.71%) — but this is misleading in isolation, since
  both categories start from a much smaller base (2,649 and 38,240 units
  respectively) than 2/3-wheelers. High percentage growth on a small base
  is a different story than the sustained high-volume growth seen in
  2/3-wheelers — worth stating both the % and the absolute numbers together
  in the final report to avoid overstating the passenger/commercial trend.

In [45]:
year_cols = ["2019", "2020", "2021", "2022", "2023"]

master_global_ev_share = df_global.melt(
    id_vars=["Region"],
    value_vars=year_cols,
    var_name="year",
    value_name="market_share_pct"
)
master_global_ev_share["source_file"] = "RS_Session_266_AU_552_D_i.csv"

master_global_ev_share.info()
master_global_ev_share

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Region            20 non-null     object
 1   year              20 non-null     object
 2   market_share_pct  20 non-null     float64
 3   source_file       20 non-null     object
dtypes: float64(1), object(3)
memory usage: 772.0+ bytes

    Region  year  market_share_pct                    source_file
0    China  2019              93.2  RS_Session_266_AU_552_D_i.csv
1   Europe  2019               2.9  RS_Session_266_AU_552_D_i.csv
2      USA  2019               1.2  RS_Session_266_AU_552_D_i.csv
3   Others  2019               0.6  RS_Session_266_AU_552_D_i.csv
4    China  2020              73.5  RS_Session_266_AU_552_D_i.csv
5   Europe  2020               4.1  RS_Session_266_AU_552_D_i.csv
6      USA  2020               1.2  RS_Session_266_AU_552_D_i.csv
7   Others  2020               4.7  RS_Session_266_AU_552_D_i.csv
8    China  2021              61.2  RS_Session_266_AU_552_D_i.csv
9   Europe  2021               5.7  RS_Session_266_AU_552_D_i.csv
10     USA  2021               1.0  RS_Session_266_AU_552_D_i.csv
11  Others  2021               1.2  RS_Session_266_AU_552_D_i.csv
12   China  2022              78.8  RS_Session_266_AU_552_D_i.csv
13  Europe  2022               8.7  RS_Session_266_AU_552_D_i.csv
14     USA  2022               2.4  RS_Session_266_AU_552_D_i.csv
15  Others  2022               5.7  RS_Session_266_AU_552_D_i.csv
16   China  2023              68.2  RS_Session_266_AU_552_D_i.csv
17  Europe  2023              18.8  RS_Session_266_AU_552_D_i.csv
18     USA  2023               2.2  RS_Session_266_AU_552_D_i.csv
19  Others  2023               5.0  RS_Session_266_AU_552_D_i.csv

## Insights: Global Comparison

- China dominates global EV market share throughout 2019-2023 but its
  dominance is not steady — it dropped sharply from 93.2% (2019) to a low
  of 61.2% (2021), before recovering to 78.8% (2022) and settling at 68.2%
  (2023). Overall it fell ~25 percentage points across the period even
  with the 2022 rebound.
- Europe shows the clearest sustained growth trend of any region — rising
  from 2.9% (2019) to 18.8% (2023), roughly a 6.5x increase in relative
  share, with growth in every single year of the period.
- USA's share stayed low and largely flat (1.0-2.4%) across all 5 years —
  showing much slower relative EV market growth compared to Europe over
  this period, at least by this market-share measure.
- Overall takeaway: the global EV market is diversifying away from being
  almost entirely China-driven, with Europe the clearest beneficiary of
  that shift; useful context for framing India's own EV growth (covered
  in other themes) against the global backdrop.